### PR TITLE
Camera recoil

### PR DESCRIPTION
**Pull request by MeteoricDragon**
I added the new "CameraRecoil" script as a component to PlayerAdvanced in unity. but I didn't see it appear as a changed file in the commit I submitted.  I say this partially because unity told me that the script part of the component was missing. So I removed the component and added a new component to the CameraRecoiler script.  You may need to check it before running it.  It works on my side.

### CODE REVIEW

**Comment by Interkarma** [comment]
Cheers. :) Since you're not sending to the existing branch, and this appears to be a whole self-contained PR, I will remove my previous branch with the old code and rebase this to a new branch. Please send any bug fixes to the branch up to the point it is merged back to master.

**Comment by Interkarma** [comment]
Merged into my CameraRecoil branch on my end. I'll add any comments against this PR after testing.

**Comment by MeteoricDragon** [comment]
Thanks, feel free to experiment with line 34's value.  50 might be too low for the max recoil of the very high setting.  The other settings will scale appropriately to the new maximum.

**Comment by Interkarma** [comment]
Thank you! I'll merge this one to master now as the code all appears to be solid enough.

I'm not seeing any head recoil in the latest version however, even with max setting and taking large hits on low-level characters. A quick step-through shows that everything seems to be executing OK. I'll leave this one for you to take a look at when you have time.

If you have any fixes/changes for this feature, please just send to master from here. All the code will be there soon.

**Pull request merged**
