### PR TITLE
Fix issues with guild NPCs that have no/bad building faction data

### PR DESCRIPTION
**Pull request by ajrb**
I'm back. :-)

### CODE REVIEW

**Comment by Interkarma** [comment]
>I'm back. :-)

Wohoo! :) Will get this merged soon mate.

**Comment by ajrb** [comment]
That's how I do it.
git fetch upstream
git rebase upstream/master

**Comment by TheLacus** [comment]
Also `git pull --rebase upstream master`

**Comment by TheExceptionist** [comment]
Thanks

**Pull request merged**
