### PR TITLE
Import guild memberships from classic

### PR DESCRIPTION
**Pull request by Allofich**
Imports guilds from classic, including rank and time of last rank change.

The only used guild value I know of that is not imported is one that seems to be involved in guild promotions and rewards.

@ajrb I had to make a couple guild-related methods public so I could access them, I hope that's alright with you. Also I had to do some conversion work to match to the days-since-promotion that you're using. Classic goes by minutes. (As far as I have seen classic always uses minutes for game time related calculations)

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
i like this

**Comment by ajrb** [comment]
Hey Allofich, looks good to me man! There's a little re-factoring I'd like to do once this is merged to re-protect some methods - if that would be ok with you? Mainly move some of the creation of memberships to be responisbiliity of GuildManager. I'm really pleased you've done this work though, mainly cos I didn't want to. :-D

**Comment by ajrb** [comment]
Oh, and I used days simply to make the conditional check simpler and easier to understand. I gave no thought to classic TBH, so thanks for having my back on that one!

**Comment by Interkarma** [comment]
Looks good to me, and as @ajrb is happy, I'll just merge this now. He can add his own refinements later as needed.

You guys are seriously awesome!

**Pull request merged**
