### PR TITLE
Updating 0.6 to current master and reviewing conflicts

### PR DESCRIPTION
**Pull request by Interkarma**

### CODE REVIEW

**Comment by Interkarma** [comment]
Updating 0.6 to be in line with master. Only two minor conflicts between master and 0.6 to resolve.

**Comment by Interkarma** [comment]
Closing this PR, made a mistake trying to update this branch to current master.

**Comment by Interkarma** [comment]
@Allofich, I made a mistake trying to bring 0.6 up to date with master and get the enemy casting stuff in there. Had a minor conflict to resolve and somehow ended up merging 0.6 into master. Thank you git for giving me a heart-attack.

I reverted that merge in master, and 0.6 is showing no changes. But a fresh compare between branches no longer yields any changes. Any idea what I've mucked up here? Cheers.

**Comment by Allofich** [comment]
If worst comes to worst, I still have 0.6 as it was, saved locally.

**Comment by Interkarma** [comment]
How about I revert my reversion so master is back in line with 0.6 again? Then this PR won't look like such a disaster. I'm actually pretty happy with 0.5 now with enemy casting in, can probably just keep pushing forwards. I don't think anything you've done in 0.6 so far will cause any problems, and no blocking issues to creating a stable build.

**Comment by Interkarma** [comment]
Awesome, thank you. I've reverted revert and master should be in line with everything up to your first round of changes in 0.6 again now.

**Pull request closed without merging**
