### PR TITLE
Fix several mistakes in Text.rsc

### PR DESCRIPTION
**Pull request by df-ferital**
This PR is a first attempt at correcting TEXT.RSC errors. The following ones were fixed:

- All directions given by NPCs should be fixed. No more _The best way to go The Green Hedgehog is southwest of here_. Now, the NPC will properly answer _The best way is to go southwest of here_. I tried to correct all of these historical mistakes, but a review would be greatly appreciated.
- Knightly order descriptions are now using proper guild names. No more Knights of the Dragon described as Order of the Dragon. Also, the Knights of the Hawk are properly assigned to Antiphyllos.
- Replaced the non-existent %pc macro (even in classic) with %fpc.
- Fixed the "Freshly burried dead" issue reported here: http://forums.dfworkshop.net/viewtopic.php?f=12&t=2692&sid=892c8fc88eac4bc46f06d9cdcf49eb78
- Replaced many flawed "its" and "Its" with "it's" and "It's".

### CODE REVIEW

**Comment by df-ferital** [comment]
More fixes:
- Correct many spelling mistakes
- Replace all "daedra" occurences with "Daedra" as well as "daedric summonings" with "Daedra summonings"
- Replace Dimunition [sic] with Slowfalling in Alteration magic school description (Diminution spell effect was removed in classic patch 1.04.191)
- Replace Acidic Field with Toxic Cloud in Destruction magic school description
- Replace Detection with Water Walking in Thaumaturgy magic school description

**Comment by Interkarma** [comment]
This is really excellent and thorough work. Will merge this soon, thank you so much! :)

**Comment by df-ferital** [comment]
Thanks for the review :)

**Comment by df-ferital** [comment]
I updated the last commit with the following fixes:
- Fix Jack of Trades description (macro %cs does not exist): http://forums.dfworkshop.net/viewtopic.php?f=5&p=50344&sid=f90c0be7d010eceed8921e4c281cfc7b#p50344
- Replace `a bit of a walk. Just go %di` with `%di, with a bit of a walk` as we could come across wrong sentences like `Go a bit of walk. Just go north`.

**Comment by df-ferital** [comment]
Updated again to remove all references to %2com as this macro is not implemented in classic.

**Pull request merged**
