### PR TITLE
Update npc presence when rest dialog dismissed

### PR DESCRIPTION
**Pull request by ajrb**
I get annoyed when resting in a guild for npcs to arrive and have to exit and reenter the building for them to show up. Added a check when rest dialog is dismissed.

### CODE REVIEW

**Comment by petchema** [comment]
Will they also be able to disappear as you sleep?
It's certainly more logic, but some people may whine (say, rest in fighters guild to (ab)use trainer...)

**Comment by ajrb** [comment]
You think it should only work to make NPCs appear. Yeah, I think I agree actually, since I've done that myself. So PR updated!

**Comment by ajrb** [comment]
When I originally implemented NPC schedules and closed the classic loophole allowing save/load to have the shopkeep vanish for easy stealing, the possibility of ejection was discussed and discarded for core DFU.

**Comment by Interkarma** [comment]
Love it, thank you! :)

**Pull request merged**
