### PR TITLE
FACTION.TXT fixes

### PR DESCRIPTION
**Pull request by df-ferital**
This fixes a lot of errors in FACTION.TXT. My fix is built on top of DelphiSnake's one, which was itself built on top of PLRDLF's fix. To check the list of DelphiSnake's changes: http://slushpool.dfworkshop.net/fact-changes.txt

What I also changed:
- Lady Bridwell is now properly listed under the Daggerfall faction: doing quests for her will now also raise reputation with Daggerfall.
- The Knights of the Hawk are now properly listed under Antiphyllos: this fixes an issue in-game were a member of this order could't rent a room for free in the region taverns.
- King of Worms now appears on top of The Necromancers, as every other guild leader.
- King of Worms and The Necromancers race set to -1 (just for the sake of consistency, since this field is not used at all in classic nor in DFU).
- Necromancers male and female flats are set to "174 3" and "174 5" respectively, instead of using King of Worms' one.
- The Septim Empire's region is set to -1 and its guild group to 15 (Region).
- Isle of Balfiera ruler is set to 11 (Lady) and its race to 3 (Breton).
- Lord Khane is renamed to Lord Kain to remain consistent with lore.
- Added a female flat to the Court of Lainlyn.
- Changes in allies and enemies:
  - Baron Shrike is now the enemy of both Lord Kain and Lord Harth while the last two are allies.
  - The Host of the Horn and The Host of the True Horn are enemies.
  - Gortwog and Princess Elysana are now allied to Lord Woodborne.
  - Prince Helseth is now allied to Princess Morgiah and Karethys.
  - Princess Morgiah is now allied to the King of Worms.
  - King of Worms and The Underking are enemies.
  - Necromancers and Agents of the Underking are enemies.
  - The Temple of Stendarr is now the enemy of Boethiah instead of its ally (makes much more sense).
  - Lord Quistley is no longer allied to Lady Doryanna Flyte.
  - Charvek-si is no longer allied to Sentinel.
  - Br'itsa is no longer allied to Lord Harth.
  - The School of Julianos is no longer allied to Clavicus Vile.
  - The Temple of Kynareth and Lord Coulder are no longer allied to Daggerfall.

Concerning allies and enemies, there is probably more to do.

### CODE REVIEW

**Comment by deepfighter** [comment]
Thanks Ferital for those preliminary changes. I tried once to build up on DelphiSnakes changes myself for Classic, but stopped because of time constraints and as it was quite overwhelming to get started. I know that this is tremendous work, and probably not the last time to check on this file - so it's great to start and further fix this. I do have some comments regarding your mentioned changes. Next to clear bug fixes, like the male/female flat changes, I would like to know the source/reason behind some others. 

Just wondering - it seems that now some factions won't have any ally or enemy - wouldn't that confuse or unbalance things to much?

> **Gortwog** and Princess Elysana are now allied to Lord Woodborne.

May you explain, why Gortwog and Woodborne should be allies? From a Lore-perspective it's quite the opposite, as Gortwog send Orcs and tried to save Lysandus ([https://www.imperial-library.info/content/daggerfall-narrative](here)).

> Charvek-si is no longer allied to Sentinel.

Why that? She is officially a Healer in Castle Sentinel and still stands there. Wouldn't it be mysterious, when she wouldn't be associated to Sentinel?

> **The Temple of Kynareth** and Lord Coulder are no longer allied to Daggerfall.

It's quite debatable. Isn't Kynareth still the goddess-protector of Daggerfall? And lore-wise - Vanech, the Arch-Priest of Kynareth was a (extrem) party in the Treaty of Gradkeep, with a strong influence on Daggerfall. He was the reason, why this became a bloodshed in the first place ([https://www.imperial-library.info/content/daggerfall-narrative](here)). And why Lord Coulder? There seems to be no reason for him not to be associated with Daggerfall, like intended by the developers. Why remove him?

> The Temple of Stendarr is now the enemy of Boethiah instead of its ally (makes much more sense).

Can you elaborate further? I know you can't take some of those for granted and some got retconned in later games, but if you change that, you may have also change Azura and Molag Bal. Regarding Stendarr and Boethiah you may argue that they have at least the same opponent and Boethiah supports everyone, which is against one of their enemies - "the enemy of my enemy is my friend"-thing. :-D

> Br'itsa is no longer allied to Lord Harth.

Why? If she is still allied with Lord Kaine, I see no point in her not also trusting Harth.

**Comment by df-ferital** [comment]
Thanks for taking the time to review @deepfighter! I will revert some of the additions I made on top of DelphiSnake's one regarding allies and enemies. Those you don't agree with are mostly based on DelphiSnake's own suggestions: http://slushpool.dfworkshop.net/fact-ideas.txt.

Regarding Gortwog, I agree with you, I didn't check the lore and didn't remember this part of the main quest precisely, as I didn't do it in years. I only made the change since in the original FACTION.TXT, Lord Woodborne has both Gortwog and Elysana as allies. This error may be related to the fact that Daggerfall Chronicles states that Gortwog orcs helped Woodborne to kill Lysandus, which was probably the original story, before it got modified for the final release. So the correct change to make there is to remove Gortwog from Lord Woodborne allies. I will fix this.

Concerning Br'itsa, the fact she would be allied with Lord Harth does not make any sense actually. She's not allied with Kain either, where did you get this information from? The UESP states that Br'itsa helped Harth, but this is not sourced. I can revert this change though, since these NPCs do not appear in-game, so this will not cause any harm.

For Charvek-si and Lord Coulder, I removed their allied status with their respective region since not only no other individual is allied with a region, but in-game, individuals are excluded from the rumor mill, meaning that their allies and enemies are never updated. I did the same for the Temple of Kynareth as it was the only temple allied to a region, but I have no problem to revert this change.

Regarding Boethiah, I found this really weird that such a Daedra Prince who is the ruler of plots of murder, assassination and treason would be allied to the holy order dedicated to the God of Mercy and Justice. And since no other Daedra Prince have holy orders as allies, but some have them as enemies, I'm quite sure this is an error.

**Comment by df-ferital** [comment]
PR modified:
- Gortwog and Lord Woodborne are no longer allied.
- Br'itsa is allied to Lord Harth again.
- Temple of Kynareth is allied to Daggerfall again.
- Lord Bridwell race set to Breton (3), though, again, this is purely informative as this is not used in-game.
- Isle of Balfiera ruler really set to Lady (12 instead of 11 in the original PR).

**Comment by deepfighter** [comment]
Thanks for your explainations! I just hope you don't read them as critique on your work. I know of DelphiSnake's - which is quite knowledgable lore-wise - suggestions and honestly didn't understand them completely back then, either. 

>Concerning Br'itsa, the UESP states that Br'itsa helped Harth, but this is not sourced, nor do we have any information on her relation with Kain. I can revert this change though. As these NPCs do not appear in-game, this will not cause any harm.

Neither do I know more about her. It's just an assumption by UESP because of this FACTIONS.TXT. I am thinking as a general rule of thumb - if we have no lore sources or any other (technical) clues, that these assumptions in the file are wrong and they make sense in a way, why change it? Therefore (as you did yet) I would personally keep Br'itsa in this case how it is, independently, if those are implemented or not - if the latter, who tells that this won't happen by the modding community at a later stage?. The same with setting races like Bridwell - even though those may not used yet, it's good to have them corrected. :)

> For Charvek-si and Lord Coulder, I removed their allied status with their respective region since not only no other individual is allied with a region, but in-game, individuals are excluded from the rumor mill, meaning that their allies and enemies are never updated. I did the same for the Temple of Kynareth as it was the only temple allied to a region, but I have no problem to revert this change.

Understand the technical cause behind this change. If that's the reason I agree with you. And if I see that correctly, Charvek-si is still associated with Sentinel (region: 21). That was a wrong understanding from my side, as I thought you remove the associated region from her, but it's "just" the ally-status. Just for clarification, what would that mean, if we go the other way and give all characters their corresponding region as ally - they do not appear in the rumor tag, then?

> And since no other Daedra Prince have holy orders as allies, but some have them as enemies, I'm quite sure this is an error.

That's the convincing point for me. :) This seems really like an oversight, then. I just wanted to raise awareness, that lore-wise some strange collaborations and alliances could occur, especially in the realm of Aedra/Daedra.

Thanks for your reverted changes. I have nothing to add. :)

**Comment by df-ferital** [comment]
> Thanks for your explainations! I just hope you don't read them as critique on your work. I know of DelphiSnake's - which is quite knowledgable lore-wise - suggestions and honestly didn't understand them completely back then, either.

Don't worry, in fact I'm quite happy that you took the time to review this PR :)

> Understand the technical cause behind this change. If that's the reason I agree with you. And if I see that correctly, Charvek-si is still associated with Sentinel (region: 21). That was a wrong understanding from my side, as I thought you remove the associated region from her, but it's "just" the ally-status. Just for clarification, what would that mean, if we go the other way and give all characters their corresponding region as ally - they do not appear in the rumor tag, then?

This would mean that every quest completed for an NPC would also raise reputation with the NPC region and I don't think this is what was intended there. Similar to Charvek-si, Popudax is a member of the Mages Guild and also the court sorcerer of Daggerfall but does not have Daggerfall as an ally.

> Thanks for your reverted changes. I have nothing to add. :)

But if you think of something else, don't hesitate to tell it here. There is still room for improvment.

**Comment by Interkarma** [comment]
Thank you @df-ferital, and thanks for helping with review @deepfighter! Very much appreciate the assist.

**Pull request merged**
