### PR TITLE
Automap - major overhaul - micro map, custom user notes (markers), portals, fixes

### PR DESCRIPTION
**Pull request by Nystul-the-Magician**
new features:
- micro map
- custom user notes (markers)
- user note text and beacon info on mouse hover over in status bar (bottom of automap window)
- rotation pivot axis now has indicator arrows to better indicate its purpose
- teleporters are marked on the map now once pc discovered them (travelled through them) - left double click on a portal will show the connected portal (this is done by a short 1sec camera movement animation that will end with the camera showing the other portal)
fixes:
- entrance beacon/position is now correctly set for interiors when loading a save game where pc is in building
- lighting fixes

map behavior changes:
- 3d view is now standard view (as requested by some forum users)

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
one little thing that is a bit annoying is that the position of the cursor that shows the character input in the input message box (DaggerfallInputMessageBox) is off quite a bit for longer texts with sdf rendering enabled

**Comment by Nystul-the-Magician** [comment]
found an issue with the colliders - closed for now until fixed

**Comment by Nystul-the-Magician** [comment]
fixed now

**Comment by Nystul-the-Magician** [comment]
@interkarma: do you want me to merge latest work on teleporter markers into this pull request as well?
or should I do a separate pr?

**Comment by Interkarma** [comment]
Hey! That looks interesting. :) Could you tell me more about this one? Can the player only activate when within a certain range of the teleport marker, or is this more of a debug feature than for gameplay?

**Comment by Nystul-the-Magician** [comment]
it is just for visualizing the teleporters on the map after player discovered them (travelled through portal)
then you get the purple portal marker for both the entrance portal as well as the exit portal on the map
double clicking the portal marker will move the automap camera position to the connected portal (the player won't move, just the automap view gets centered on the other portal endpoint - the centering is done with iTeens to move the camera smoothly to the other portal endpoint within 1 second of time)

**Comment by Interkarma** [comment]
Ah, I get it now! That's a very helpful feature, I love it. Sure, happy for it to be in this PR. I'm slowly working through all of these now.

**Comment by Interkarma** [comment]
>one little thing that is a bit annoying is that the position of the cursor that shows the character input in the input message box (DaggerfallInputMessageBox) is off quite a bit for longer texts (with sdf rendering enabled the position is more off but even with classic font it is off the longer the text gets)

This sounds like it might be a scale issue. I'll take a look to see if I can help before merging.

I've also inadvertently created a merge conflict in Automap.cs when fixing a simple null check. I'll revert my change for now and we can make null check part of this commit.

**Comment by Interkarma** [comment]
Actually Nystul, could you take a look at conflict in Automap.cs? The whole file appears to be in conflict. Perhaps a rebase needed?

I've removed my null check from Automap.cs and can add again later.

**Comment by Nystul-the-Magician** [comment]
I manually resolved the conflict and added your changes to SaveStateAutomapInterior() function as well
I was too afraid to rebase stuff since I never done that before and feared to break the repository

**Comment by Interkarma** [comment]
It's all good, I'm just happy with it being able to merge. Thank you! :)

**Pull request merged**
