### PR TITLE
[RFC] Travel map dot outlines

### PR DESCRIPTION
**Pull request by petchema**
Make region maps more accessible to color blinds by adding an outline to location pixels.
It actually makes it easier to point at locations, so it could be seen as a general improvement.

Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&p=43718#p43717

The implementation uses Panels for the outlines, works well but may be too hackish?
Also, ir probably needs to be made an option or have a keyboard toggle.
outlines 2 - 128

### CODE REVIEW

**Comment by petchema** [comment]
Made it a new setting (default on, it really helps with visibility)

**Comment by ajrb** [comment]
Nice to have an accessibility option, but not convinced it should be on by default as it changes the look from classic quite a bit.

**Comment by petchema** [comment]
Yup, seems fair

**Comment by Interkarma** [comment]
I like this one a lot. Thank you for your efforts on this @petchema and communicating with forum members to get a good result.

**Pull request merged**
