### PR TITLE
Enable custom items to be added by mods

### PR DESCRIPTION
**Pull request by ajrb**
Builds on the rudimentary support I added for the locator device 2 years ago. I have attempted to implement this with as light a touch on the codebase as possible.

Now uses the item templates file and defines a template index which for custom items is used for the group index as well.

Regarding paperdoll items, Weapons and armor are fully functional and tested. Clothing may need a bit more work which I will look at soon but I wanted to get this on the list of PRs so people can start to review the changes. Corresponding changes can be found in my Archs mod and Loot Realism on this branch: https://github.com/ajrb/dfunity-mods/tree/moderateWeaponMaterials

Loot realism now adds 2 new weapons: Archers Axe and Light Flail, and also a new lighter set of mail armor allowing players who can't wear plate to get high level material armor pieces.

NOTE: This PR builds on #1747 and as such contains all of those changes as well. (first 9 commits) Either review & merge this one and I'll close that one, or review & merge #1747 first and then this should lose all those changes to allow it to be reviewed separately.

### CODE REVIEW

**Comment by ajrb** [comment]
Have added a fix for weapons using archive 233 instead of 234 for female characters. Included in this PR so I could ensure it was integrated and working with custom items. If thsi PR is rejected then I will make a separate PR for this fix. (hopefully that will not be the case) Please see this thread: https://forums.dfworkshop.net/viewtopic.php?f=22&t=3465&p=41489#p41487

Also added a conditional to the change TheLacus made to scroller component. The base image has zero size for new images that don't appear in the classic data files so the tex dimensions do have to be used in that case.

**Comment by Interkarma** [comment]
Hi mate, I just merged #1747 before getting to this one. I wanted to spend a bit more time on this one because of the number of changes, so I merged the smaller number of changes first.

**Comment by ajrb** [comment]
Sure no problem, updated this with most recent changes in master so the PR is now only the custom items changes. If you have any queries just ask.

**Comment by Interkarma** [comment]
Seems straight-forward and I wasn't able to produce any problems. Thanks for writing such consistently good code. It makes changes like this much easier to digest. :)

**Comment by ajrb** [comment]
@Interkarma Thanks for checking it, and thanks for the complement. It's nice to hear... I mean *I* usually think my code is good, but I'm probably biased. :-)

**Pull request merged**
