### PR TITLE
Completed keyboard bindings and reset defaults

### PR DESCRIPTION
**Pull request by JustinSteele02**
- Set and save keyboard bindings fully functional
- Can no longer exit with invalid configuration. Duplicates are
highlighted and popups prevent closing window
- Defaults tab button returns keys to DFUnity defaults

Couldn't find the "you have multiple assignments..." message in the text.rsc dump. Probably a hard string, but it's not in our HardStrings class yet so I just added it manually for the moment.

### CODE REVIEW

**Comment by Allofich** [comment]
Sounds like nice work!

> Couldn't find the "you have multiple assignments..." message in the text.rsc dump. Probably a hard string, but it's not in our HardStrings class yet so I just added it manually for the moment.

It's in FALL.EXE. As far as I know those are being added in to the HardStrings, so I think you can include in there.

**Comment by Allofich** [comment]
I gave it a quick run, and it seems to work well. Nice job! One thing I noticed is that the key names seem to be a little high, though. In original Daggerfall they seem to be level with the text describing the action. I think lowering them down one "pixel" (as in one of the scaled up pixels from the original artwork) would do the trick.

**Comment by JustinSteele02** [comment]
Yup you're right, they're off center a bit. I was planning on fixing that and merging it later along with the mouse sensitivity window.

**Comment by Interkarma** [comment]
This is great! Thank you for all your work on this. I'll give this one more test and merge back to master in next 24 or so.

**Pull request merged**
