### PR TITLE
Fix hit point calculations

### PR DESCRIPTION
**Pull request by Allofich**
For level up, I was just adding the Career.HitPointsPerLevelOrMonsterLevel. Actually it is a random number between this value and half of it, plus the endurance modifier.

### CODE REVIEW

**Comment by Allofich** [comment]
Also fixed the formula for determining the player's initial health. This is not affected by the endurance modifier and does not involve any randomness. I'm pretty sure this is what is used for human enemies' health, too.

**Comment by Interkarma** [comment]
This seems very nice on a quick playthrough. Monsters felt a bit too paper-thin before and now they feel more like Daggerfall. This will be awesome once all the proper to-hit and other combat equations are accounted for. Great work! 👍 

Speaking of which, are melee formulas also something you're considering building out? I have no complaints if that's a direction you want to head down.

**Comment by Allofich** [comment]
> Speaking of which, are melee formulas also something you're considering building out?

Yes, although the damage and to-hit calculations seem to have a lot of different factors to them and I haven't figured it all out yet. By the way, I thought that some time ago another contributor added damage based on weapon type, but was that dropped for some reason?

**Comment by Interkarma** [comment]
I vaguely recall the PR for this. All I can remember is that it needed some work and contributor never returned to complete, so PR was closed. It was a far cry from real combat formulas though.

**Pull request merged**
