### PR TITLE
Fix more one-way staircases

### PR DESCRIPTION
**Pull request by petchema**
Forums:
https://forums.dfworkshop.net/viewtopic.php?t=3482 (original) 
https://forums.dfworkshop.net/viewtopic.php?t=6720 (new)

### CODE REVIEW

**Comment by petchema** [comment]
[SAVE16.zip](https://github.com/user-attachments/files/16043795/SAVE16.zip)
[SAVE17.zip](https://github.com/user-attachments/files/16043796/SAVE17.zip)
[SAVE18.zip](https://github.com/user-attachments/files/16043797/SAVE18.zip)
[SAVE19.zip](https://github.com/user-attachments/files/16043798/SAVE19.zip)
[SAVE20.zip](https://github.com/user-attachments/files/16043799/SAVE20.zip)

**Comment by petchema** [comment]
Could we filter on some "Interior ID"? Because it gets very repetitive...

[SAVE1036.zip](https://github.com/user-attachments/files/16044642/SAVE1036.zip)
[SAVE1035.zip](https://github.com/user-attachments/files/16044644/SAVE1035.zip)
[SAVE1034.zip](https://github.com/user-attachments/files/16044646/SAVE1034.zip)
[SAVE1033.zip](https://github.com/user-attachments/files/16044647/SAVE1033.zip)
[SAVE1032.zip](https://github.com/user-attachments/files/16044648/SAVE1032.zip)
[SAVE1031.zip](https://github.com/user-attachments/files/16044649/SAVE1031.zip)
[SAVE1030.zip](https://github.com/user-attachments/files/16044650/SAVE1030.zip)
[SAVE1029.zip](https://github.com/user-attachments/files/16044652/SAVE1029.zip)
[SAVE1028.zip](https://github.com/user-attachments/files/16044653/SAVE1028.zip)
[SAVE1027.zip](https://github.com/user-attachments/files/16044655/SAVE1027.zip)
[SAVE1026.zip](https://github.com/user-attachments/files/16044656/SAVE1026.zip)
[SAVE1025.zip](https://github.com/user-attachments/files/16044657/SAVE1025.zip)
[SAVE1024.zip](https://github.com/user-attachments/files/16044658/SAVE1024.zip)
[SAVE1023.zip](https://github.com/user-attachments/files/16044659/SAVE1023.zip)
[SAVE1022.zip](https://github.com/user-attachments/files/16044660/SAVE1022.zip)
[SAVE1021.zip](https://github.com/user-attachments/files/16044661/SAVE1021.zip)
[SAVE1020.zip](https://github.com/user-attachments/files/16044662/SAVE1020.zip)
[SAVE1019.zip](https://github.com/user-attachments/files/16044663/SAVE1019.zip)
[SAVE1017.zip](https://github.com/user-attachments/files/16044664/SAVE1017.zip)
[SAVE1016.zip](https://github.com/user-attachments/files/16044665/SAVE1016.zip)
[SAVE1015.zip](https://github.com/user-attachments/files/16044666/SAVE1015.zip)
[SAVE1014.zip](https://github.com/user-attachments/files/16044667/SAVE1014.zip)
[SAVE1013.zip](https://github.com/user-attachments/files/16044668/SAVE1013.zip)
[SAVE1012.zip](https://github.com/user-attachments/files/16044669/SAVE1012.zip)
[SAVE1011.zip](https://github.com/user-attachments/files/16044670/SAVE1011.zip)
[SAVE1010.zip](https://github.com/user-attachments/files/16044671/SAVE1010.zip)
[SAVE1009.zip](https://github.com/user-attachments/files/16044672/SAVE1009.zip)

**Comment by KABoissonneault** [comment]
This change is probably good. I know there's the idea that everyone should just be using UBLaMF, but I know no matter how much we raise awareness, some people are going to want to play without mods, and then we need to fix it at a DFU level.

One question I have is, are these changes guaranteed not to interfere with modded versions of those blocks? I don't see a check in the code, but it's possible those Block Index / Entry Index / Model Id are only used in classic data.

**Comment by petchema** [comment]
[SAVE1057.zip](https://github.com/user-attachments/files/16044883/SAVE1057.zip)
[SAVE1056.zip](https://github.com/user-attachments/files/16044884/SAVE1056.zip)
[SAVE1055.zip](https://github.com/user-attachments/files/16044885/SAVE1055.zip)
[SAVE1054.zip](https://github.com/user-attachments/files/16044886/SAVE1054.zip)
[SAVE1053.zip](https://github.com/user-attachments/files/16044887/SAVE1053.zip)
[SAVE1052.zip](https://github.com/user-attachments/files/16044888/SAVE1052.zip)
[SAVE1050.zip](https://github.com/user-attachments/files/16044889/SAVE1050.zip)
[SAVE1048.zip](https://github.com/user-attachments/files/16044890/SAVE1048.zip)
[SAVE1047.zip](https://github.com/user-attachments/files/16044891/SAVE1047.zip)
[SAVE1046.zip](https://github.com/user-attachments/files/16044892/SAVE1046.zip)
[SAVE1045.zip](https://github.com/user-attachments/files/16044893/SAVE1045.zip)
[SAVE1044.zip](https://github.com/user-attachments/files/16044894/SAVE1044.zip)
[SAVE1043.zip](https://github.com/user-attachments/files/16044895/SAVE1043.zip)
[SAVE1042.zip](https://github.com/user-attachments/files/16044896/SAVE1042.zip)
[SAVE1041.zip](https://github.com/user-attachments/files/16044897/SAVE1041.zip)
[SAVE1040.zip](https://github.com/user-attachments/files/16044898/SAVE1040.zip)
[SAVE1039.zip](https://github.com/user-attachments/files/16044899/SAVE1039.zip)
[SAVE1038.zip](https://github.com/user-attachments/files/16044900/SAVE1038.zip)
[SAVE1037.zip](https://github.com/user-attachments/files/16044901/SAVE1037.zip)

**Comment by petchema** [comment]
Interkarma may have decided to include those patches in base game because they're somewhat game breaking (player is trapped inside the building if s.he manages to get upstairs.
About compatibility with mods, I have no idea. I'm not adding a new mechanism here, just patching more buildings

**Comment by KABoissonneault** [comment]
Yeah I get it. It's really more that the project is at a point where I don't want to break people's setups for as long as I can avoid it. Gonna have to investigate, or wait for someone with more expertise to weigh in on the compatibility (@XJDHDR maybe?)

**Comment by petchema** [comment]
I think I'm done with that specific interior, I looked around, mostly in large desert cities (that kind of building only occurs in large towns)
[SAVE21.zip](https://github.com/user-attachments/files/16046470/SAVE21.zip)
[SAVE22.zip](https://github.com/user-attachments/files/16046471/SAVE22.zip)
[SAVE23.zip](https://github.com/user-attachments/files/16046472/SAVE23.zip)
[SAVE24.zip](https://github.com/user-attachments/files/16046473/SAVE24.zip)

**Comment by XJDHDR** [comment]
I'm pretty sure the `IsBadInteriorModel` method is only called when blocks are being built from the BSA and not when the data comes from a mod. It might be a good idea to check though.

**Review by KABoissonneault — APPROVED** [review]
I have no verified every save, but I do appreciate the documentation, really. I believe the changes do affect modded blocks using this model, but who knows if anyone does.
We'll see, maybe it's a bad model to begin with. The good impact is probably better than the risk.

**Pull request merged**
