### PR TITLE
Trees: fixes and tweaks

### PR DESCRIPTION
**Pull request by TheLacus**
It's still a bit off, don't know if due to terrain resolution or something i can fix.

treeposition 1
treeposition 2

### CODE REVIEW

**Comment by Interkarma** [comment]
I had a similar issue with aligning tree billboards. The secret sauce for me was to use Terrain.SampleHeight() rather than the raw terrain data itself. Unity returns a much more accurate result within the scene. Have a look at TerrainHelper.LayoutNatureBillboards() around line 460 for where I do this.

Let me know if there's anything I can do to help. :)

**Comment by TheLacus** [comment]
Thanks for the tip, but i tried working on the y axis and it didn't work. Whatever value i assign i get the same result in game, only x and z affects the position. Tree is always placed correctly on terrain on height.

This 2d position on terrain plane is assigned as values in range 0-1, relative to terrain; this means that i'm calculating position as currentTile/detailResolution. Don't know if there is a way to get a more precise value than this, i'll get to do more tests and report again.

**Comment by TheLacus** [comment]
Anyway, i'd like to include a WindZone. I tested it as a component of WeatherManager go and it works fine, do you think is ok there? Or you prefer i add it via script only if modding is enabled?

**Comment by Interkarma** [comment]
My misunderstanding then, I thought you were having troubles with the vertical placement. I will formulate a better answer for you when I can. :)

**Comment by TheLacus** [comment]
I'll keep an eye on this but i don't think is an important issue for now.
What about wind? No rush but i wonder if you missed my second comment :)

**Comment by Interkarma** [comment]
I'm sorry for the delayed reply. I got a bit distracted and forgot to loop back to you.

Happy for WindZone to be part of WeatherManager if that makes things easier for you. If there's any performance impact, I only ask the component is disabled at startup if mods not enabled. :)

**Comment by Interkarma** [comment]
For the layout process - I'm not sure but if you need to provide a range of 0-1, could you keep things within the same domain as LayoutNatureBillboards()? The X/Y loop is stepping through tiles relative to MapsFile.WorldMapTileDim, so u=x/(MapsFile.WorldMapTileDim-1) and v=y/(MapsFile.WorldMapTileDim-1) should come very close as the tile grid is already considered to cover the whole terrain tile edge to edge.

The terrain terrainData.detailResolution you're using in ImportNatureGameObject() is set by the terrain sampler's heightmap dimension, which by default is 129 (close, but slightly off from MapsFile.WorldMapTileDim). It's also possible for a replacement terrain sampler to use a higher resolution heightmap, which would really throw things out of kilter as the heightmap dimension would no longer be close to WorldMapTileDim.

I hope that helps. If you still get stuck, I'd be happy to try and help. I'd just need some quick steps on setting up a test environment to reproduce problem properly. :)

**Comment by TheLacus** [comment]
Thanks for the detailed answer. You're right, i had the solution in front of my eyes the whole time, thank you for pointing out WorldMapTileDim :)

**Pull request merged**
