### PR TITLE
Allow access to hide billboards for mods.

### PR DESCRIPTION
**Pull request by concarne000**
Here is a solution I've found to give public access to force hide a billboard, specifically with the intention of implementing 3D models, without impacting the engine or other mods, while also being able to access the engines concealment for magic effects.

### CODE REVIEW

**Comment by ajrb** [comment]
I think this is the wrong approach to take for this. @TheLacus if you disagree and want me to explain why and how I think this should be done, please say.

**Comment by TheLacus** [comment]
Hi! I appreciate the effort but a mod that replace mobile billboards with mobile models should replace the actual asset, not just hide it. Other mods are either unaffected by this change or strictly require a billboard, so the game shouldn't tell them that one is used while is actually not true.

Mobile Npcs are instantiated from `DaggerfallMobilePerson [Standalone]` prefab, which holds everything related to npc behaviour and management of entity itself, while its child `MobilePersonBillboard` only has `MobilePersonBillboard` instance and the `MeshRenderer`.

What we need is an interface, let's call it `IMobilePersonBillboard` that defines non-private properties and methods of `MobilePersonBillboard` and is implemented by this class as well as any custom component used by mods for models.

```cs
public interface IMobilePersonBillboard
{
    bool IsIdle { get; set; }
    bool IsUsingGuardTexture { get; }
    void SetPerson(Races race, Genders gender, int personVariant, bool isGuard);
    Vector2 GetSize(); // Renamed from GetBillboardSize()
}
```

**Comment by TheLacus** [comment]
@Allofich Can we add public property `IsGuard` to `MobilePersonNPC` and remove `IsUsingGuardTexture` from here?

**Comment by Allofich** [comment]
@TheLacus, I think that should be fine. I think I did it that way because the original game was identifying guard MobilePersonNPCs by them using the index for the guard graphic, and not with a separate isGuard-type property.

**Comment by Interkarma** [comment]
@TheLacus what are your thoughts on this one? Should it be closed, as you had another direction in mind?

**Comment by TheLacus** [comment]
> 
> 
> @TheLacus what are your thoughts on this one? Should it be closed, as you had another direction in mind?

Yes, i was waiting for review of #1598 but i think i can do it now.

**Pull request closed without merging**
