### PR TITLE
RmbBlockEditor file cleanup

### PR DESCRIPTION
**Pull request by KABoissonneault**
This is what appears in my Git status when I checkout master and open Unity now

image

I wish I'd caught this before merging the PR.

Just adding the meta files with default values - if anything else was intended, it should be fixed by whoever knows what these files should have.

I'm adding Editor settings to the .gitignore. I figure these files should be local to each repo

### CODE REVIEW

**Review by Jagget — APPROVED** [review]

**Comment by petchema** [comment]
Mmmh so far we've committed *.meta files in the repository, and personally I think it would be safer in the long run to also commit those (even if right now it will raise merge conflict for some), say if we want to tweak the metas of the PNG files. 
Not sure what those *.json files contain though (buildings-catalog.json etc)

**Comment by KABoissonneault** [comment]
> Mmmh so far we've committed *.meta files in the repository, and personally I think it would be safer in the long run to also commit those (even if right now it will raise merge conflict for some), say if we want to tweak the metas of the PNG files. Not sure what those *.json files contain though (buildings-catalog.json etc)

And I am, for files which are persistent. 

Settings are trickier, they only get created after usage. These would get lots of local changes, so even if I committed an empty version of those files, they would show in the Git status after usage without any intention of actually committing them to the repo. I think .gitignore for any settings is fine (I'd even add ProjectSettings/EditorSettings.asset to be honest, it's a permanent change for me).

**Comment by Podleron** [comment]
Ah, hold on, you've actually added the meta files, not removed them.
I thought that any generated files should not be included in the code, but to be honest I don't know enough about them and what they do exactly. I will go read up on it and in the meantime the change is ok by me.

**Review by Podleron — APPROVED** [review]

**Comment by KABoissonneault** [comment]
@petchema You think you could approve the PR? You're one of the few people who count for the "2 approving reviews" requirements (sorry Podleron, you don't have write access to this repo).

I wouldn't say no to some of my other PRs too :P

**Review by petchema — APPROVED** [review]
LGTM

**Review by Interkarma — APPROVED** [review]

**Pull request merged**
