### PR TITLE
fix regression in PlaySource.cs

### PR DESCRIPTION
**Pull request by petchema**
Fix regression I made in a3479c7c that made Lysandus silent :(

### CODE REVIEW

**Comment by petchema** [comment]
[SAVE197_vengence.zip](https://github.com/Interkarma/daggerfall-unity/files/3005631/SAVE197_vengence.zip)

**Comment by petchema** [comment]
With that fix I uncover another regression: now "Vengeance" plays inside buildings too.
git bisect points at 80b4f62c
[SAVE89_inside_vengeance.zip](https://github.com/Interkarma/daggerfall-unity/files/3005826/SAVE89_inside_vengeance.zip)

**Comment by Interkarma** [comment]
>With that fix I uncover another regression: now "Vengeance" plays inside buildings too, or even exit the city.
Thank you. It appears my previous fix also stops tasks from shutting down correctly. I'll handle this a different way shortly.

**Comment by Interkarma** [comment]
Thanks for spot on both of these @petchema :) I've just merged a fix for the WhenTask issue. I included this fix as well since I needed it for testing. Cheers!

**Pull request closed without merging**
