### PR TITLE
Grammar and typo fixes

### PR DESCRIPTION
**Pull request by Arcane21**
Fixed many improperly spelled items, capitalized many proper nouns, some consistency fixes

### CODE REVIEW

**Comment by deepfighter** [comment]
The "Ark'ay" fix in the books.txt shouldn't be changed, as it's supposedly the intended title "Ark'ay". That the books contradicts this is in typing in the last line "Arkay" is imho no typo, as nobody knows how it was to be intended (his mortal name Ark'ay and his god name Arkay, maybe?). This book got some revisions during the development process and this could be just be forgotten to be changed and therefore - lore-wise - both names are correct and thus it should be kept like in classic.

**Comment by Arcane21** [comment]
> The "Ark'ay" fix in the books.txt shouldn't be changed, as it's supposedly the intended title "Ark'ay". That the books contradicts this is in typing in the last line "Arkay" is imho no typo, as nobody knows how it was to be intended (his mortal name Ark'ay and his god name Arkay, maybe?). This book got some revisions during the development process and this could be just be forgotten to be changed and therefore - lore-wise - both names are correct and thus it should be kept like in classic.

Good point. Vaermina and Vaernima also seem to both be correct according to lore, so I'll revert that.

**Comment by bansheexyz** [comment]
Some of your changes are correct, but some are not. I'd study the language more before attempting to make sweeping changes like this:

-The articles before unique items are not really an error, totally preferential change here.
-"Final" should not be "Finale", the error here is the missing word "battle" after final. Finale is used for performances and it's clearly not a metaphor here. See line 84/85 for this "battle" to be referenced again.
-Emperor should be capitalized there, it is a title and titles only get capitalized before names. You can google this rule.
-The changes to "Mortalcreature" aren't necessary, it's basically a nickname being given to you. There's no way these two words would've been accidentally combined and capitalized in three separate places.

**Comment by Arcane21** [comment]
> Some of your changes are correct, but some are not. I'd study the language more before attempting to make sweeping changes like this:
> 
> -The articles before unique items are not really an error, totally preferential change here.
> -"Final" should not be "Finale", the error here is the missing word "battle" after final. Finale is used for performances and it's clearly not a metaphor here. See line 84/85 for this "battle" to be referenced again.
> -Emperor should be capitalized there, it is a title and titles only get capitalized before names. You can google this rule.
> -The changes to "Mortalcreature" aren't necessary, it's basically a nickname being given to you. There's no way these two words would've been accidentally combined and capitalized in three separate places.

As for the first one, good point, I'll tweak this to be correct.

The second one is also a good point, I capitalized it in a fww other places it was lowercase, can;t believe I missed that.

As to the third, I'm aware it was likely intentional, but it still doesn't make much sense. I get the dialouge is supposed to reflect a broken form of English, but it still comes off as grammatically bizzare, even for writing with a broken speech pattern. I left the rest alone because it made perfect sense to be rendered as broken English, but I cannot recall any instance of spoken broken English rendered in script format with words joined together like that, especially two words that form natural conclusions to their syllables.

I'll revert it, but it just looks wrong, even for writing that is supposed to resemble broken English.

**Comment by bansheexyz** [comment]
I forgot a word myself and edited my comment. I meant to say "emperor" should *not* be capitalized there. For example: "Bow to your emperor" is correct and "Bow to Emperor Uriel" is correct. It's only capitalized when it's before a name.

https://grammarist.com/style/president/

**Comment by Arcane21** [comment]
> I forgot a word myself and edited my comment. I meant to say "emperor" should _not_ be capitalized there. For example: "Bow to your emperor" is correct and "Bow to Emperor Uriel" is correct. It's only capitalized when it's before a name.
> 
> https://grammarist.com/style/president/

I see. I'll revert that to be correct as well.

**Comment by tolbell** [comment]
> As for the Articles before certain artifacts, not only was it not consistent with later games,

That doesn't make it a typo.

> it wasn't even consistent within Daggerfall's nomenclature for artifact names.

It could also be said that the names without "The" are inconsistent with those that have it. If some are prefixed with "The" and others are not, it seems arbitrary to toss out all the ones that have "The."

> Further, the names would indicate false or lesser copies exist due to the "The" article, and since they are one of a kind, they made no sense at all.

I disagree that this is implied by the article. My understanding is that "The" implies that there is only one of a given object.

There is still one instance of "Mortal creature" left to be reverted.

**Comment by Arcane21** [comment]
> > As for the Articles before certain artifacts, not only was it not consistent with later games,
> 
> That doesn't make it a typo.
> 
> > it wasn't even consistent within Daggerfall's nomenclature for artifact names.
> 
> It could also be said that the names without "The" are inconsistent with those that have it. If some are prefixed with "The" and others are not, it seems arbitrary to toss out all the ones that have "The."
> 
> > Further, the names would indicate false or lesser copies exist due to the "The" article, and since they are one of a kind, they made no sense at all.
> 
> I disagree that this is implied by the article. My understanding is that "The" implies that there is only one of a given object.
> 
> There is still one instance of "Mortal creature" left to be reverted.

I've fixed the remain instance mentioned for Dagon's quest.

As to the Artifacts, I looked up the names for all the games on the UESP (a source even the official developer have admitted to consulting to keep the lore straight), and aside from Daggerfall, all the other games have remained consistent with the name changes I made to the artifacts. I understand it may irritate some who are obsessed with the original text remaining inviolate, but for reasons of consistency, since all the artifacts and the Daedric Princes they are associated with are supposed to the same artifact for all games in the series, just used by different characters throughout the series timeline, then I must fall on the side of making sure the text remains consistent with the overall series canon.

Also, granted, Molag's Mace appears in Skyrim as the "Rusty Mace" before Molag Bal restores it to full power and gives it to you as a reward, but it's still the same mace, just drained of it's power before the quest end powers it up and hands you the full powered version, the "Mace of Molag Bal"

Ergo, keeping the "The" is just adhering to a name change that does not mesh with the rest of the series canon

**Comment by tolbell** [comment]
In that case, I suggest you change the title. In my mind, this is more controversial than simply fixing typos and grammar mistakes.

**Comment by Arcane21** [comment]
> In that case, I suggest you change the title. In my mind, this is more controversial than simply fixing typos and grammar mistakes.

Noted. I'd like to have input from the project lead on this before I do anything one way or another.

**Comment by Interkarma** [comment]
I'd prefer the artifact names remain as classic. I actually changed many of these early in the project as you have here, and received some push-back. I now see this as a uniquely Daggerfall quirk that has been present for decades. And the classic names are also referenced elsewhere in relation to Daggerfall. For example, the UESP artifacts page for Daggerfall below. While it's still easy enough to tell what is what, this is something I'd prefer to keep like classic.

https://en.uesp.net/wiki/Daggerfall:Artifacts

I think the other changes are fine though. I'll check through everything else before merging and let you know if any other comments. Thank you. :)

**Comment by Arcane21** [comment]
> I'd prefer the artifact names remain as classic. I actually changed many of these early in the project as you have here, and received some push-back. I now see this as a uniquely Daggerfall quirk that has been present for decades. And the classic names are also referenced elsewhere in relation to Daggerfall. For example, the UESP artifacts page for Daggerfall below. While it's still easy enough to tell what is what, this is something I'd prefer to keep like classic.
> 
> https://en.uesp.net/wiki/Daggerfall:Artifacts
> 
> I think the other changes are fine though. I'll check through everything else before merging and let you know if any other comments. Thank you. :)

Understood. I will comply ASAP.

**Comment by Interkarma** [comment]
Looks good, thank you. :)

**Comment by tolbell** [comment]
I know I'm late, but I have one more objection to this. I understand why you wanted to change the name of "The Hircine Ring" (although the argument can be made that the word "hircine," while being the name of a daedric prince in TES, is also a regular English adjective). Regardless, "The Hircine's Ring" certainly has... an odd ring to it. As a native speaker, I don't think one would usually put "The" before a possessive noun - "Kevin's house" sounds fine, but not "The Kevin's house."

If it must be changed, I suggest "The Ring of Hircine" (which is consistent with other Daggerfall artifacts such as "The Ring of Namira") or simply "Hircine's Ring" (as in Morrowind).

**Comment by Interkarma** [comment]
That's fair, and I agree. Have reverted that name change now.

**Pull request merged**
