### PR TITLE
1383 macro %di expansion can fail and crash the game

### PR DESCRIPTION
**Pull request by JorisVanEijden**
Suggested fix for #1383

### CODE REVIEW

**Comment by Interkarma** [comment]
Hi there! Thank you for the PR, but I can see lots of changes across unrelated files and part of the code. Could you please tidy up PR just to the minimum required number of line changes. Thank you. :)

**Comment by JorisVanEijden** [comment]
The whitespace changes are caused by the project's .editorconfig
The change in Questing/Person.cs is to fill the location reference when someone's home/location is mentioned.
The change in TalkManager.cs does look weird. Maybe something went wrong in merging.
The change in Text/ConversationText.txt is to provide a better fitting "error message" when the direction is unknown because you're at the same location.
".. located in the vicinity of here" looks better than the current ".. located never mind... of here"

I will look into forcing my IDE to ignoring the project's .editorconfig if whitespace changes are not acceptable (you may want to consider changing the .editorconfig in that case)
I will look at the changed made in TalkManager.

Do you want me to split the PR into 2?
1 for fixing the bug (only adding a null-check) and 1 for improving the way the %di macro works?

**Comment by Interkarma** [comment]
Interesting, which IDE are you using? It's easy enough to change .editorconfig, I just haven't experienced this myself or from contributors. I'm using Visual Studio on this end.

Two PRs would be ideal, thank you! I can then fast-track the crash fix into next builds and give the %di changes some extended testing time.

BTW, I'm also taking a look at issue #1408 - there's a possibility I might also make edits to Person.cs. I won't be sure until I dive into it some more. I'm sure we can work any conflicts easily enough, just wanted to give you a heads-up.

**Comment by JorisVanEijden** [comment]
I'm using Rider and it applies the settings from .editorconfig to every file committed. I've disabled .editorconfig support now for this project.

#1425 is the PR for the nullreference

**Comment by Interkarma** [comment]
I've merged the two fixes #1425 and #1426 now. Thank you for splitting these out and working with me on the formatting side of things. It was much easier to review. Very much appreciated!

I'll close this one now as the edits are covered by those two PRs.

**Pull request closed without merging**
