### PR TITLE
Adjust listbox row count for small font

### PR DESCRIPTION
**Pull request by numidium**
Addresses the bug described in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1792

### CODE REVIEW

**Comment by Interkarma** [comment]
Cheers. :)

**Comment by petchema** [comment]
That seems like a very adhoc fix, what about
```
diff --git a/Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs b/Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
index e0777dd5..6f457959 100644
--- a/Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
+++ b/Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
@@ -289,8 +289,7 @@ namespace DaggerfallWorkshop.Game.UserInterfaceWindows
                 return;
             }
 
-            DaggerfallListPickerWindow advantagePicker = new DaggerfallListPickerWindow(uiManager, this);
-            advantagePicker.ListBox.Font = DaggerfallUI.SmallFont;
+            DaggerfallListPickerWindow advantagePicker = new DaggerfallListPickerWindow(uiManager, this, DaggerfallUI.SmallFont, 12);
             advantagePicker.OnItemPicked += AdvantagePicker_OnItemPicked;
 
             items = isDisadvantages ? disadvantageStrings : advantageStrings;
@@ -393,8 +392,7 @@ namespace DaggerfallWorkshop.Game.UserInterfaceWindows
             } 
             else
             {
-                DaggerfallListPickerWindow secondaryPicker = new DaggerfallListPickerWindow(uiManager, this);
-                secondaryPicker.ListBox.Font = DaggerfallUI.SmallFont;
+                DaggerfallListPickerWindow secondaryPicker = new DaggerfallListPickerWindow(uiManager, this, DaggerfallUI.SmallFont, 12);
                 secondaryPicker.OnItemPicked += SecondaryPicker_OnItemPicked;
                 secondaryPicker.OnCancel += SecondaryPicker_OnCancel;
                 foreach (string secondaryString in secondaryList)
```

instead?

**Comment by Interkarma** [comment]
Yes, that would be better. I now recall that's why I added font and the row count to the constructor back in 98c58072. I had intended to let @numidium know (because these didn't exist when he first wrote the custom class creator) so he could fix that list count, and then promptly forgot. 🥇 

My apologies numidium, would you mind reworking change to use the constructor options as @petchema  has flagged? :)

**Comment by numidium** [comment]
@Interkarma No problem, I'll take care of it.

**Pull request merged**
