### PR TITLE
Guard improvements

### PR DESCRIPTION
**Pull request by Allofich**
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1637

### CODE REVIEW

**Comment by Allofich** [comment]
Various improvements to guards:

- Guards spawning from MobileNPCs (including guard MobileNPCs) now are looking in the same direction as the MobileNPC was looking when they first spawn

- Hitting MobileNPC guards is now an assault, not a murder (MobileNPC guards "dying" in one hit and counting as a murder is an issue in classic as well). If the EnemyMobile guard is killed, then it become murder.

- Hitting MobileNPC guards will now instantly create an EnemyMobile guard in the same spot (intended to already be doing this, but because I skip over disabled NPCs when choosing where to spawn guards from, it wasn't happening). The EnemyMobile guard will take a hit/parry as usual. (Had to make Start() in EnemySounds into Awake() so that the dfAudioSource will be ready in time)

- Slight redo of guard spawning code. Only MobileNPC guards in classic spawn range are selected for spawning MobileEnemy guards from. I had originally made all MobileNPC guards spawn into MobileEnemy guards instantly, but after I added the code to periodically update nearby MobileNPC guards into MobileEnemy guards when the player is being chased by guards, it was no longer necessary to make them all into MobileEnemy guards immediately.

**Comment by Allofich** [comment]
BTW, I added some code that I think will work OK for spells hitting MobileNPCs, but spells are currently not damaging MobileNPCs, they just go through them without colliding. I this was working before? Arrows work.

**Comment by Allofich** [comment]
> I'll take a look at this before merging just in case there's a simpler fix.

This PR doesn't contain a fix. I just added some code to account for attacking guards next to the existing part for attacking MobileNPCs. Since spells aren't hitting MobileNPCs, though, it's untested.

**Comment by Interkarma** [comment]
Thanks for clarifying. I haven't reviewed code, just responding to comments. Will loop back when I can to look closer. :)

**Comment by Allofich** [comment]
I'll test this in a while against the new master code since spells on NPCMobiles should be working.

**Comment by Allofich** [comment]
Yikes, does not work right. Don't shoot a spell at a MobileNPC with this PR with the sound on right now, or you'll get an explosion of overlapping spell impact sounds as it repeatedly hits an exception in the PR code. I'll fix it.

**Comment by Allofich** [comment]
Fixed. BTW I still had a couple instances where a spell seemed to go through a target. Once with a MobileNPC and once with a MobileEnemy guard, although it worked most of the time. Might still be some tuning needed there.

**Pull request merged**
