### PR TITLE
implemented SpyMaster pop-up message box like in classic, quest residence discovery behavior changed

### PR DESCRIPTION
**Pull request by Nystul-the-Magician**

### CODE REVIEW

**Comment by Interkarma** [comment]
I'm amazed we're finally at the point where even more obscure features like the spy master are being implemented. Very exciting! I'll merge when I can.

**Comment by Nystul-the-Magician** [comment]
spymaster was quite easy to do (unless I have overseen some features):
-) always knows answers
-) only gives anyinfo messages instead of rumor messages when a quest topic is asked about under "tell me about" - basically all %hnt2 macros become %hnt macros :)

**Comment by Interkarma** [comment]
Still impressed! :)

**Comment by Nystul-the-Magician** [comment]
thank you ;)

**Pull request merged**
