### PR TITLE
Merge sceneCache to master

### PR DESCRIPTION
**Pull request by Interkarma**
Opening PR for merging sceneCache branch to master. Will test branch and merge to master as soon as possible.

### CODE REVIEW

**Comment by ajrb** [comment]
The sceneCache branch should be deleted not merged!

**Comment by Interkarma** [comment]
If that's how you want to do it... I'll close this PR now and you can resend a new PR to master when ready. Cheers.

**Comment by ajrb** [comment]
You just merged with master - sorry if I was not clear enough. Delete the sceneCache branch and test master - if you find any issues I will fix ASAP over the weekend. I've tested pretty thoughroughly.

**Comment by Interkarma** [comment]
I didn't merge with master - I just created the PR for later, and it's closed now. Nothing changed in master yet on my end. :)

There were several conflicts with this sceneCache > master PR as well. Assuming that's why you wanted to do things the other way. I'll just hang tight until you advise.

**Comment by ajrb** [comment]
Look at master on github, and see my other comment on other thread. I think we need an IM connection.

**Comment by Interkarma** [comment]
On the same page now - just replied in other thread. All aboard. :)

**Pull request closed without merging**
