### PR TITLE
Fix player dying on starting new game

### PR DESCRIPTION
**Pull request by Allofich**
Looks like I shouldn't have changed the thing. I didn't test my changes in the last PR on starting a new character. This PR should fix it.

### CODE REVIEW

**Comment by Allofich** [comment]
Hold on, I think I can simplify the fix.

**Comment by Interkarma** [comment]
Haha all good. Thanks for the fix. :)

And a quick thing I just thought of then - does fatigue loss respect god mode when 'tgm' is toggled on? I didn't think to look at that earlier.

**Comment by Allofich** [comment]
Oh, I just simplified the fix, but you merged it. Well, you can add the simplification to it yourself if you want. Just change the assignments to health, fatigue and magicka in AssignCharacter() to be lower case instead of upper case (PlayerEntity to DaggerfallEntity). Then you can get rid of the Mathf max statements, because the PlayerEntity OnDeath and OnExhausted events won't run anymore. Well, it's up to you.

**Comment by Allofich** [comment]
Fatigue loss does not respect god mode, no.

**Comment by Interkarma** [comment]
Please send another PR for the simplified fix. Will be happy to merge. :)

Sorry for the fast turnaround. I don't normally do merges around this time of day, but working from home and can be a little more proactive.

**Pull request merged**
