### PR TITLE
fix city gates regression

### PR DESCRIPTION
**Pull request by petchema**
Broken in 94a2c78b

Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2002

### CODE REVIEW

**Comment by Allofich** [comment]
Hm. Removing that comment causes

`Assets/Scripts/Utility/RMBLayout.cs(817,36): warning CS0219: The variable `gate' is assigned but its value is never used`

to appear in the Unity editor, but you're sure this fixes the issue? This warning is a false positive?

**Comment by Interkarma** [comment]
The component needs to be added, but it doesn't need to be stored as "gate". Can just remove that and leave the component intact for gate handling.

Thanks for looking into this Pango. :)

**Comment by Allofich** [comment]
Ah, I see. Sorry for not being more careful when I originally commented it out.

**Comment by Interkarma** [comment]
Don't worry about it, I didn't catch it when I reviewed either. :)

**Pull request merged**
