### PR TITLE
Initial version of painting info construction

### PR DESCRIPTION
**Pull request by ajrb**
Painting titles match classic.
Artist names don't match classic. 
Image not displayed yet.

### CODE REVIEW

**Comment by ajrb** [comment]
@Interkarma could you check the PaintFile class and its usage please? I copied one of the existing DF file access classes and then stripped most of the code out. I had no idea what i was doing or if what's there correctly fits the pattern you created for the DF file access classes.

**Comment by Interkarma** [comment]
That looks good to me Hazelnut. I'll merge this now and take a look at adding image support to message box over weekend. Great work!

**Comment by ajrb** [comment]
happy for you to suggest how you want it done and then I can implement the image support instead of you so you can keep focussed on fun stuff (magic) - either way is fine with me.

**Comment by Interkarma** [comment]
I just merged a very minor update to add an ImagePanel property to DaggerfallMessageBox. This should at least help you get started as you can control the entire Panel itself.

**Comment by ajrb** [comment]
Cool, I will take it from there then. Thanks. :-)

**Pull request merged**
