### PR TITLE
Fix some incorrect UV coordinates within the data files

### PR DESCRIPTION
**Pull request by df-ferital**
This provides a starting point to patch some wrong texture UV coordinates in ARCH3D.BSA at runtime.
For now, this fixes the following problems:
- Tavern pillars like in The King's Fairy, Daggerfall
- Compressed wall texture near the entrance of a weapon store like The Count's Arsenal, Newtale, Bhoriane (@petchema)
- Stretched dungeaon corridor floor (from model index 989)

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
nice great work - pillars in mages guild are suffering from the same problems ;) those bugged me for a long time - so hopefully we will get them fixed :D

**Comment by Allofich** [comment]
I'm also glad these texture issues are finally getting fixed. Thank you!

**Comment by df-ferital** [comment]
I think all interior models containing pillars are now fixed. The problem is the switch statement I used is rather big now.

Not sure if this should be merged yet, there may be a cleaner way to handle that.

**Comment by df-ferital** [comment]
Closing for now. Will open a new PR with a better algorithm.

**Comment by Nystul-the-Magician** [comment]
Would have been ok for me with the switch statement - refinement later would have been fine ;)

**Comment by petchema** [comment]
> Would have been ok for me with the switch statement - refinement later would have been fine ;)

I agree, it's fine to iterate; the first version doesn't need to be elegant if it does the job and is identified as something to improve

**Comment by df-ferital** [comment]
Ok, I reopen it :).

I have started to work on a far better solution though, which will allow to patch every bit of a BSA file. This allowed me to change the wrong texture file used for the dungeon sewer floor @petchema mentioned on the forums.

It works pretty well, but I didn't transfer patches to the pillar textures yet.

So @Interkarma, if you want to merge the current solution in the mean time, I'm ok with it :)

**Comment by Interkarma** [comment]
Happy to merge in the meantime. Thanks again for all your work on this. :)

**Pull request merged**
