### PR TITLE
Allow for longer names in location picker

### PR DESCRIPTION
**Pull request by petchema**
Answer to request #2684

- set limit to 50 characters instead of 29 when SDF fonts (that are narrower) are enabled;
- make that limit more accessible to modding (did I get that part right? I'm not familiar with that aspect)

### CODE REVIEW

**Comment by KABoissonneault** [comment]
I'm not sure public is the right accessibility yet. Usually, we would make this protected, so that a mod providing a window override can use a custom value.
Public could be right if there was a way for mods to register to an event that would let it change the value after `Setup()` (so that its value wins over the default) but before `ShowLocationPicker` (so it actually gets used). This way, mods could customize this behavior without overriding the window. I haven't looked if we have any such event

**Comment by KABoissonneault** [comment]
I'm not sure I like the explicit check for SDF vs non-SDF. Is that what we do for books and other auto-formatted text boxes? I know quest text is manually formatted to support non-SDF, but I think books are handled in code

**Comment by petchema** [comment]
> I'm not sure public is the right accessibility yet. Usually, we would make this protected, so that a mod providing a window override can use a custom value. Public could be right if there was a way for mods to register to an event that would let it change the value after `Setup()` (so that its value wins over the default) but before `ShowLocationPicker` (so it actually gets used). This way, mods could customize this behavior without overriding the window. I haven't looked if we have any such event

Okay, if simplest/most convenient way is subclassing, making it a `protected virtual` property

**Comment by petchema** [comment]
Also, the same issue happens with the list of spells (spell merchant, spellbook)

**Comment by petchema** [comment]
> but somehow it didn't work (text not clipped inside the ListBox. I'm not sure what I'm missing

My current hypothesis is that ShowLocationPicker is calling AddItem() of the ListBox before its parent DaggerfallListPickerWindow has been SetUp(), which is a problem because it's AddItem() that propagates the RestrictedArea of the ListBox to its elements

**Comment by petchema** [comment]
My analysis was correct, and simplest fix I could think of was to subclass DaggerfallListPickerWindow to delay calls to listBox.AddItem(s) to the end of Setup()
I end up fixing locations list, spell mechant/spell book lists, bookshelves list

**Comment by petchema** [comment]
sdf locations list after
nosdf locations list after

**Comment by petchema** [comment]
books list before
books list after

**Comment by petchema** [comment]
spells list before
spells list after

**Comment by petchema** [comment]
Could be factorized further if we decide DaggerfallListPickerWindow should always use restricted area, or would benefit from a constructor with a List<string> to initialize its content; I just tried to keep changes as local as possible.

**Comment by petchema** [comment]
While I'm fixing form issues, fixing banking inventory amount whose length was not increased when wagon content display was added

**Comment by KABoissonneault** [comment]
Can anyone point me to where I can get the French localization installed, so I can try the width changes?

**Comment by petchema** [comment]
> Can anyone point me to where I can get the French localization installed, so I can try the width changes?

Last binary release (1.1.1a) is on NexusMods: https://www.nexusmods.com/daggerfallunity/mods/456

Sources are on GitHub, to get the development version you can just copy the content of this directory in StreamingAssets: https://github.com/Daneel53/DFU-en-francais/tree/main/French%20files%20for%20DFU

**Review by KABoissonneault — APPROVED** [review]
Not exactly a fan of the duplicated derived class. From what I understand, the ListBox of the picker does not set its own Position and Size until you push the window, so you cannot set the `.RectRestrictedRenderArea = new Rect(listBox.Position, listBox.Size)` before adding the elements... I feel like they could be a way to generalize this into a `DaggerfallFixedListPickerWindow`, that sets the listbox size and restricted render area on construction rather than on Setup

Gonna approve this anyway. I'll let this on hold for some time in case you want to make that new class. Otherwise, we'll stick with that

**Comment by petchema** [comment]
That `DaggerfallFixedListPickerWindow` approach, moving some UI code to places inconsistent with other windows, makes me more nervous than a few duplicated lines...

**Review by KABoissonneault — APPROVED** [review]

**Pull request merged**
