### PR TITLE
Implement player leveling

### PR DESCRIPTION
**Pull request by Allofich**
Implements player leveling. As far as I know everything that should be implemented is implemented. Unity saves will at some point need to store the sum of starting skills used in calculating levels. For now this value is estimated based on the current level.

### CODE REVIEW

**Comment by Interkarma** [comment]
Holy crap dude you are killing this, awesome work. 👍 

I can add these items to DFUnity saves tomorrow. Just to summarise, you need the following saved and loaded:

* PlayerEntity.skillUses[]
* PlayerEntity.timeOfLastSkillIncreaseCheck
* PlayerEntity.startingLevelUpSkillSum
* PlayerEntity.currentLevelUpSkillSum

Please just let me know if I've missed anything. I'm about to head out for the night and didn't have long to review code.

**Comment by Allofich** [comment]
> Holy crap dude you are killing this, awesome work. 
Thanks. I happen to have a lot of free time at the moment to work on this, but maybe not so much in the near future.

> PlayerEntity.skillUses[]
> PlayerEntity.timeOfLastSkillIncreaseCheck
> PlayerEntity.startingLevelUpSkillSum

Yes for these. If you want to change the data type, like if you don't want to use an array or something, that is fine.

> PlayerEntity.currentLevelUpSkillSum

This can be calculated from the current player skill values so it isn't necessary to save it.

**Comment by Interkarma** [comment]
I've added those three items to save/load now. Please test and let me know if anything else I can do.

Great work. :)

**Comment by Interkarma** [comment]
Hey just some feedback on levelling. I started a level 1 warrior and went for a run through PH in both classic and DFUnity. Here's a few UI quirks I noticed on our end - nothing major at all. :)

* Once ready, level-up did not trigger by resting like it does it classic. In fact it didn't trigger until I fast travelled to a city.
* I heard the level-up chime but character window didn't open automatically.
* Stat rollout was not visible on character window so impossible to assign points or click exit (screens below)
* Can still close with ESC key though without assigning points. Will need to prevent ESC from closing this window when a level-up in progress.

Otherwise, the level-up skill increases and notifications seemed to work perfectly as per classic. Excellent work!

Please just let me know I anything I can do to assist with the above. If you're not available to fix, I will loop back and look at these as soon as I have some time away from quest system.

levelup-norollout1
levelup-norollout2

**Comment by Allofich** [comment]
At the moment I can only confirm the ESC key issue. Did you have this issue with the current master?

playerEntity.RaiseSkills(), which sets in motion the level-up progress, is called in DaggerfallRestWindow's OnPop(). It's also called when fast traveling, so I don't see why fast travel would work for you while resting wouldn't. Do you have the save file?

**Comment by Interkarma** [comment]
Don't have a save file for this from before issue. My test process was new character > clear PH > rest a lot. Level didn't ding until fast travel. Let me try and reproduce and I'll send it through when I can. :)

**Comment by Allofich** [comment]
> My test process was new character > clear PH > rest a lot. 
I tried the same, but didn't have a problem. I just tried again (latest master), and still didn't have a problem, so unless it was caused by some change you had in a test branch or something, there must be something more to it. If you can reproduce the problem and the cause remains elusive maybe we can each record a video of our attempts and find out where our behavior is diverging.

**Comment by Interkarma** [comment]
Thanks for taking a look! I haven't been able to reproduce the level-up not happening until fast travel. That was probably just an edge-case of some kind. I'm not too worried about that one right now. :)

I have been able to reproduce the stat spinner issue each time however. The difference I think is that I'm testing in a build. It works fine inside the editor, but doesn't display in build. No exceptions in output log either >.<

**Comment by Interkarma** [comment]
I can't see anything wrong with your code to add/remove the stat spinner either. Must be something up with the UI loading on my end. I never tested that spinner outside of character creation either, so probably not surprising it turned out to be less robust than expected.

I'm happy to see this as a problem on my end if you like. I'll dive into it when I can ahead of the next builds dropping.

**Comment by Allofich** [comment]
Thanks, I think I would like if you would take on the task of trying to fix it, then.

**Comment by Allofich** [comment]
I can reproduce when testing in a build, too. A few other things I noticed:
1. The problem will happen with a classic save, too, so it's not related to having used the stat spinner in character generation.
2. If you build an executable (regardless of whether you then run it), and then if you run in the editor after that, the problem will happen when running in the editor. If you close and re-open Unity, or if you double-click the DaggerfallUnityGame.unity scene to "restart" it, then the problem won't be there when you run in the editor.

**Comment by Allofich** [comment]
Another thing, I just tried with the latest Unity, 5.6.1f1, and the problem still exists there.

**Comment by Allofich** [comment]
Looks like I fixed the problem by just more closely copying the way the statsRollout is made in character creation. I don't know why I didn't try that before. I don't quite understand the difference between instantiating something with a new object in the class definition and doing it in the setup() method, but that seems to be what does it. I'll make a PR.

**Comment by Interkarma** [comment]
Great work, thank you for persisting with this. You've saved me a loop back later to look into this. 👍 

I'm about to shut down for the night. Will merge in change in morning when I'm a bit fresher. Cheers!

**Pull request merged**
