### PR TITLE
Refactor TransportManager

### PR DESCRIPTION
**Pull request by zaklaus**
Implementation of a horse mount (or dismount when already on a horse/cart) for G key. This required some changes to the `TransportManager` to make sure transportation change conditions are kept in sync via a public API. `ToggleMount()` can easily mount or dismount a horse if conditions are met.

I can optionally get rid of the G key shortcut, if wanted.

NOTE:
Call to `ToggleMount()` works even inside of buildings or dungeons. This behaviour was kept intentionally to allow mods to use mounts even inside interiors. Of course, the front-end logic defaults to classic behaviour and only allows you to toggle mount in the exterior.

Introduced an option in the Enhancements section called `HorseMountShortcut`.

### CODE REVIEW

**Comment by petchema** [comment]
They're forward and backward KeyBind.txt compatibility issues with this patch, which can be a problem because it's a settings file (hence shared among all instances, and not cleaned by reinstalling DFU):
- If you had something already bound to G key, bindings play musical chairs, each one getting its default binding (I think) until everything is assigned a separate key;
- Either way, in keybindings setup screen the G binding appears in front of "Steal mode", right below "Transport". All bindings after that are shifted one place;
- If a KeyBind.txt with the new horse mount keybind is read by a version of DFU that doesn't have that feature, all bindings are lost (no bindings in KeyBind.txt, everything bound to "None" in setup).

**Comment by zaklaus** [comment]
Thanks for the report, I will adjust the changes accordingly.

**Comment by ajrb** [comment]
I think this is probably mod territory since there are no plans to expand the keybindings screen in DFU.

**Comment by zaklaus** [comment]
I've edited the InputManager to support these issues better in the future. Unknown actions will be ignored (and saved on exit). As for the `MountHorse` particularly, I believe it could be moved onto a mod territory, in that case I'd still recommend cherry-picking TransportManager changes, so that these 
 related actions will be kept in sync across the codebase.

**Comment by zaklaus** [comment]
I've separated input changes into 2 branches. This PR now only contains changes made to the TransportManager and relevant facilities. zaklaus:keybindings contains `InputManager` changes as well as the G keybind for mount toggle.

**Comment by zaklaus** [comment]
Once I return home, I would share the toggle mount mod, which would make use of this PR specifically.

**Comment by Interkarma** [comment]
Hello @zaklaus! :)

Thank you for your work here, but I'm not sure why the changes are necessary. It seems possible to create all of this functionality in a mod without refactoring TransportManager. Could you please outline the core issue that requires these changes?

**Comment by zaklaus** [comment]
Hi,

I originally wanted to create a simple toggle horse mod on a hotkey, however I've noticed that there wasn't an API for checking whether the horse is available. I've noticed the UI logic directly accesses the player's inventory to find out if he owns a special item (horse), which in turn would enable the horse button in the transport menu.

Since I needed to do the same check on the mod side, I found it redundant and easier to just present an API for easily checking whether the player owns a horse/cart with a simple method to easily change to either of those modes (`ToggleMount()`).

It is possible this isn't really required, since the core will probably never deal with transportation mode changes outside of the UI logic (T menu), but having an API to check for requirements instead of accessing the inventory directly to figure out if I can saddle a horse just felt more clean.

**Comment by Interkarma** [comment]
Thank you, I understand where you're coming from now. I'm happy for TransportManager to expose the HasHorse, etc. helpers. And while ToggleMount() is rather specific to your mod, it's a simple helper and I don't mind it being there. I also really appreciate that you trimmed this one down earlier after feedback from the others. Will test and merge this one in next few days.

**Comment by zaklaus** [comment]
Thank you, it was a nice experience exploring the codebase.

**Comment by bansheexyz** [comment]
Just wanted to add that I personally like your idea here, zak. Toggling between foot and horse with "T" instead of bringing up a menu seems like it would work well.  You could force the cart-drawn horse if a cart is owned, and then obviously do ship when standing in ocean water. I wonder why classic thought a menu was necessary? Anyway, fairly simple mod that saves a click, not up to me but seems like a good stock option.

**Pull request merged**
