### PR TITLE
Implement regional building answers

### PR DESCRIPTION
**Pull request by Allofich**
Turns out there's keys in the mapTable records for which types of buildings exist in each location.

In classic asking for armorer is bugged and always returns 0, but there was a gap in the flags and it seems to match for armorer, so this PR uses it.

The question text is still unimplemented.

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
I can take a look at the question text - should be not that hard - just have to find some time to do it ;)

**Comment by Allofich** [comment]
The question text looks to be the same as for local buildings, so I just re-used that.

**Comment by Nystul-the-Magician** [comment]
awesome job ;)

**Comment by Interkarma** [comment]
You guys rock my world. :)

I'm being smashed by work in my last couple of weeks before leave. Will get these all merged soon, and should have my life back to normal by xmas. Thanks for your patience with me.

**Comment by Allofich** [comment]
That's what I figured. :) Whenever you've got time.

**Pull request merged**
