### PR TITLE
Test around; find out

### PR DESCRIPTION
**Pull request by andrew-raphael-lukasik**
# What

A foundational setup to execute automated gameplay (play mode) tests. It includes few test examples to help everyone figure out how to write their own test cases.

Test will fail if an exception is thrown anywhere. So it won't catch all the types of errors by itself. For the exception-less cases place `Assert.IsTrue()` to make sure the code throws when some specific data is outside of valid range.

One important requirement of this setup is an [assembly definition](https://github.com/andrew-raphael-lukasik/daggerfall-unity/blob/CASE17_test-around-find-out/Assets/DFU.asmdef) that includes the game code. This means that the game code wont go into `GameAssembly.dll` (or something like that) but into `DFU.dll` now.

# Why

Merging a branch and then realizing it broke something that worked perfectly until now is not a productive way to merge branches (case of #2427 being an inspiration here). But there is a way to prevent that without sinking hours on testing everything manually every time - enter *Unit Tests*.

# Results

With a single click and bit of patience (<5min leaving Unity do it's thing) you can, for example, visit 100 locations now:

Screenshot 2022-10-11 143526

### CODE REVIEW

**Comment by andrew-raphael-lukasik** [comment]
From time to time `travel` tests fail throwing one or both of these two errors:
```
Exception: ISerializableGameObject type not implemented for DaggerfallWorkshop.Game.Serialization.SerializablePlayer
DaggerfallWorkshop.Game.Serialization.SerializableStateManager.GetStatefulGameObjectType (DaggerfallWorkshop.Game.Serialization.ISerializableGameObject sgObj) (at Assets/Scripts/Game/Serialization/SerializableStateManager.cs:498)
DaggerfallWorkshop.Game.Serialization.SerializableStateManager.DeregisterStatefulGameObject (DaggerfallWorkshop.Game.Serialization.ISerializableGameObject serializableObject) (at Assets/Scripts/Game/Serialization/SerializableStateManager.cs:264)
DaggerfallWorkshop.Game.Serialization.SaveLoadManager.DeregisterSerializableGameObject (DaggerfallWorkshop.Game.Serialization.ISerializableGameObject serializableObject) (at Assets/Scripts/Game/Serialization/SaveLoadManager.cs:553)
DaggerfallWorkshop.Game.Serialization.SerializablePlayer.OnDestroy () (at Assets/Scripts/Game/Serialization/SerializablePlayer.cs:88)
```
and
```
MissingReferenceException: The object of type 'StreamingWorld' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
DaggerfallWorkshop.StreamingWorld.get_StreamingTarget () (at Assets/Scripts/Terrain/StreamingWorld.cs:158)
DaggerfallWorkshop.StreamingWorld.CleanupUntrackedObjects () (at Assets/Scripts/Terrain/StreamingWorld.cs:1627)
DaggerfallWorkshop.StreamingWorld.StartGameBehaviour_OnNewGame () (at Assets/Scripts/Terrain/StreamingWorld.cs:1639)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.RaiseOnNewGameEvent () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:1060)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.StartTitleMenu () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:304)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.InvokeStartMethod () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:151)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.Update () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:130)
```
But are my tests at fault here or it found an actual error case? I am not sure

**Comment by Interkarma** [comment]
>But are my tests at fault here (likely) or it found an actual error case? I am not sure

Yeah, very likely the tests. SerializablePlayer definitely implements ISerializableGameObject and StreamingWorld should never be destroyed. Neither of these errors happen during play.

**Comment by andrew-raphael-lukasik** [comment]
> Yeah, very likely the tests. SerializablePlayer definitely implements ISerializableGameObject and StreamingWorld should never be destroyed. Neither of these errors happen during play.

#2444 Unit testing scored it very first lead here! I looked into that method and realized its logic was a tiny bit off and resulted in misinformation : )

**Comment by andrew-raphael-lukasik** [comment]
[56caeb1](https://github.com/Interkarma/daggerfall-unity/pull/2442/commits/56caeb1c06d5683cc69077f926f29ea1ae6cba38) Adds ability to treat game saves as a basic bug repro cases. Most bug reproductions needs more than this ofc but it is an interesting and maybe possibly useful and low-effort mechanism to do that. Worth testing out imo.

**Review by Dezzj — APPROVED** [review]
Approved

**Pull request closed without merging**
