### PR TITLE
Set gargoyle to have blood splash

### PR DESCRIPTION
**Pull request by Allofich**
I can see why it was set without, but the gargoyle should have a blood splash like in classic, because it has blood in its corpse texture.

### CODE REVIEW

**Comment by Interkarma** [comment]
At the time I wrote this, I was not able to produce any blood splashes on gargoyles in combat. Could have just been unlucky. I'll accept PR as you're confident they have blood splashes in game.

**Comment by Allofich** [comment]
> I was not able to produce any blood splashes on gargoyles in combat

Really? Well before submitting the PR I checked in classic just to be sure and they did appear. If you care enough about it I have a save game before encountering a gargoyle that I can send you, but for now I'll consider this done.

**Comment by Allofich** [comment]
Just checked in classic again and yes, it does appear for me at least.

**Comment by Interkarma** [comment]
I'm happy this is done and trusted you here enough to merge. I was probably just unlucky at the time I tested this. Cheers!

**Pull request merged**
