### PR TITLE
Class questions

### PR DESCRIPTION
**Pull request by numidium**
The UI is very spartan at the moment.  It lacks the graphical effects of classic but it functions correctly as far as I can tell from my testing.  The question text can be scrolled up and down with a mouse wheel.

I had to do a fair bit of reverse-engineering for the class choice routine.  There's a method I called GetHeaderIndex that is structured a bit strangely (two separate loops) but I was trying to mimic what I saw in the disassembly as closely as I could.

What remains to be done is to reverse-engineer the GFX files that describe the scroll images and the CEL files that animate the lightning strikes and constellations that show when a question is answered.  I also haven't yet figured out how to mask out the text that goes beyond the bounds of the scroll.

### CODE REVIEW

**Comment by Interkarma** [comment]
So happy to see a start made on this. I'll be able to help with reverse engineering CEL and GFX files soon, and no doubt others in the community will be able to help with this as well.

Looking forward to checking this out. Excellent work!

**Comment by Interkarma** [comment]
Hi @numidium, just letting you know that I've reserved engineered the GFX file format and now working on CEL. I'm building a demo class creator UI just to R&D the mechanical parts involving sky animations and scroller. When this is done, you can move over the parts you need into your UI and adapt as required. I'll be available to help as needed. :)

I don't know when I'll be done with this, but will try to get through it as quickly as I can.

**Comment by numidium** [comment]
@Interkarma, this is now in a usable state and it more or less matches classic except for the CEL animations.  I understand if you want to hold off until those are done, this is just FYI.

**Comment by Interkarma** [comment]
>@Interkarma, this is now in a usable state and it more or less matches classic except for the CEL animations. I understand if you want to hold off until those are done, this is just FYI.

Thank you! I'll get started on those CEL files soon. Looking forward to featuring your work on this in next update or two. Just incredible!

**Comment by numidium** [comment]
@Interkarma I believe this is ready to go! CEL animations and sound both work now.

**Comment by Interkarma** [comment]
Will test and merge ahead of next builds. Very much looking forward to featuring all the work you've done on this one. Well done! :)

**Comment by Interkarma** [comment]
All working very well! :)

**Pull request merged**
