### PR TITLE
WDE Object Data additions and organization

### PR DESCRIPTION
**Pull request by Cliffworms**
Added roughly 2200 models and a handful of billboards to the models and billboards data lists. Also reorganized some categories.
Full changes below : 

**New Models**

_Buildings_

Single Walls & windows
Single Floors
Single Ceilings
Single Pillars
Single half walls
Single entry ways & exits
Exterior walls and railings

_Other_

Water
Grass
Grates

**New Billboards**

Enemy Corpses
Additional skulls on pikes
Additional bucket
Additional shrub
Teleport Marker
Scarab
Religious item
Finger
Jewelry
Mantella
Alchemical ingredients

**Changes**

Added "Unused" to markers not used by DFU
Sorted the markers alphabetically
New subcategory : Religious
Cooks and serving girl NPCs are now in "Inns" with the Innkeepers
Added knights

### CODE REVIEW

**Comment by Interkarma** [comment]
That looks like painstaking work to put together. Incredible effort!

**Comment by KABoissonneault** [comment]
> That looks like painstaking work to put together
Yeah, you should have seen him after he accidentally deleted it. It took him a few hours to realize he had a backup on Google Drive.

**Comment by Cliffworms** [comment]
Hah! Not a few hours Kab. A few minutes!
Thanks! There will be another commit in a week or two with the remaining models, this time the dungeon ones that I haven't added yet.

After those, I think it'll be safe to say that the WDE contains all of Daggerfall's usable assets. (I didn't include the MQ ones because they're pretty unique)

**Comment by ajrb** [comment]
Legend!

**Pull request merged**
