### PR TITLE
Track fatigue at 64 times character sheet value

### PR DESCRIPTION
**Pull request by Allofich**
Track fatigue internally at 64 times the value shown in the character sheet, the same as classic does. This will allow for implementing loss of fatigue values in the same way.

### CODE REVIEW

**Comment by Interkarma** [comment]
Could you link me a source for this? I've never seen that fatigue is tracked internally at 64x. I've not spent much time with this however, won't be getting to this until the spells & effect update.

**Comment by Allofich** [comment]
In the Daggerfall Chronicles it says

"The PC's maximum fatigue is: ( Strength + Endurance ) * 64"

Also, using the save game editor DaggeD, the fatigue for the game you select will show roughly 64 times what the in-game character sheet shows. It will probably be a little off from when it was divided by 64 into an integer and the remainder was dropped.

Also I'm trying to reverse-engineer the game and have found that it multiplies (strength + endurance) by 64 and, when forming the string for the character sheet, it divides them by 64.

**Comment by Allofich** [comment]
Also the values listed in the Daggerfall Chronicles for the fatigue loss from various activities are

Do nothing: 11 points per minute
Swing weapon: 11 points per swing
Climb: 22 points per minute
Running: 88 points per minute
Swimming: 44 points per minute (except Argonians)
Jump: 11 points per jump

and these wouldn't make sense using the fatigue value from the Character Sheet. I loaded a game, jumped, then re-saved and checked the value in DaggeD, and it had fallen by 11 points, so these are probably accurate.

**Comment by Interkarma** [comment]
Awesome thank you. 👍

**Comment by Allofich** [comment]
This also means when you load any of your existing DF Unity save games, your fatigue bar will be nearly empty at first. But it's fine after you restore your fatigue by resting or when starting a new game, or when loading a classic save.

**Comment by Interkarma** [comment]
That's not a problem, thanks again for this. :)

**Pull request merged**
