### PR TITLE
Scene cache implementation to handle stateful game objects

### PR DESCRIPTION
**Pull request by ajrb**
This is just for you to test where I am at since probably can't do any more for a day or so. 

Looks like I will need to merge Allofich's PR once you have accepted it into master and then create a new PR for this work. I synchronised my fork before changing the shelf stocking code... but still got caught out! lol  Is no problem at all, but will be best if I do the merging I think.

### CODE REVIEW

**Comment by Interkarma** [comment]
Yay! Can't wait to play with this. I'll dive in this evening. No problems for you to merge Allofich's changes when ready.

**Comment by Interkarma** [comment]
OK, I couldn't wait haha. :)

Have started diving into this now, and OMG it just works SO WELL. I'm probably too excited to offer much in the way of constructive feedback right now, but what I've experienced so far has been seamless. Great work!

I'll calm down and do a more thorough sweep later.

**Comment by ajrb** [comment]
Have you calmed down yet?

It's pretty cool and helps give the world a feeling of reality when you re-enter a building and the doors are how you left them.

**Comment by Interkarma** [comment]
Have calmed down - still love it though. Ended up needing to work this evening so happy I had a play earlier. I should be able to tuck in over weekend and let you know any feedback. Thanks again mate. :)

**Pull request merged**
