### PR TITLE
Potion generation and enemy inventory changes

### PR DESCRIPTION
**Pull request by Allofich**
Creates potions randomly from the 20 varieties, like in classic, with correct names and values. Also works with potions imported from classic.

### CODE REVIEW

**Comment by Allofich** [comment]
I'm using an array of the prices in the function and a string array of the potion names now for simplicity, but these are actually in some kind of potion definitions in the .exe, starting at 1BA142. Each is 109 bytes long, with the first two bytes being the value.

**Comment by Interkarma** [comment]
Well done! Thank you. :)

**Comment by Allofich** [comment]
Updated. I would have made a separate PR but it would have had a merge conflict.

Now all inventory items (loot table items, maps, potions and potion recipes) are added to enemies on instantiation, not death. This is the same as classic and better in my opinion, because you would get different results if you kill an enemy, load your game, and kill it again. Also, it allows getting rid of loot piles storing a table key, which wasn't really needed.

**Comment by Allofich** [comment]
I hadn't realized there was already code to handle potion names. I changed the first commit to use the existing method.

**Pull request merged**
