### PR TITLE
Added transport menu and horse riding.

### PR DESCRIPTION
**Pull request by ajrb**
- Transport popup menu added. 
- Options enabled depending on having horse or cart in inventory.
- Horse and cart transport modes change height and speed. (cart and horse are the same to minimise changes to PlayerMotor class)
- Allow jumping since it makes sense that a horse can jump. (should be disabled for cart when PlayerMotor is rewritten)
- Play sounds for movement (clip-clop) and random neighing. (every 2-30secs)
- Transport state is correctly saved & loaded. (not imported from classic saves)
- Automatically dismount when entering buildings or dungeons.
- Fixed palette bug in CfaFile.

### CODE REVIEW

**Comment by ajrb** [comment]
One thing I should note is that I didn't add any support for modding any of this. I will look at adding this later once I see how the functionality is received.

Hopefully you like my code, I tried to fit into existing systems & conventions as much as possible. Please bear in mind I only started looking at the codebase 3 days ago and I'm not familiar with C# but it's pretty easy to pick up new languages after so many years. Been doing mainly Java for 15 years so capitalised method names kinda wierds me out... :-)

**Comment by Interkarma** [comment]
Just merged this and had a quick play. Awesome work! I'll make time for a deeper check and merge to master as soon as I can make time.

Two very minor items so far:

1. Horse might still be a touch high. In classic, I'm able to (barely) ride under the stone arch leading into Castle Daggerfall, but in DFUnity player capsule is enough to block riding under arch. If you're confident horse height is correct, could also work around this by shrinking capsule a bit more (like crouching) during riding state.

2. If player opens UI (e.g. local automap) while still moving forwards, the clip-clop sound will continue playing. This is a truly minor thing, just need to pause the audio source when game is paused (can check from GameManager).

But yeah, this is good stuff all round. Excellent work. 👍

**Comment by ajrb** [comment]
Cheers, glad you like what I've done. Hopefully closer scrutiny wont change your mind.

I thought it was a bit high still but it's still lower than classic (which is ridiculous unless it's some stilt-horse), I've lowered it to 2.8m which is the highest that will fit through the arch. This is 1.8m (large horse) + 1m (sitting rider) so is realistic. However it looks a lot lower than classic. I think the difference is probably that classic doesnt change the collision box height and DFU does. Going through the arch in classic your eyes are almost scraping the ceiling.

I found another issue, have you opened console while on a horse? :-)

**Comment by Interkarma** [comment]
Sounds reasonable on the height. Agree it's probably a collider issue more than anything else, because your height "felt" really right to me as well. I'd be just as happy for the riding collider to be slightly smaller while camera remains at same height. There's likely a happy medium in there somewhere.

Ha, didn't notice the console. All good mate, no rush. And just let me know if any help needed. :)

**Comment by TheLacus** [comment]
> One thing I should note is that I didn't add any support for modding any of this. I will look at adding this later once I see how the functionality is received.

I believe Cfa files can be considered CifRci for this purpose.

**Comment by ajrb** [comment]
> I believe Cfa files can be considered CifRci for this purpose.

What do you mean exactly? In what respect? I'm new to this so you might need to join a few dots for me.

**Comment by TheLacus** [comment]
From what i see in the code, cfa files are defined by filename, record (only one) and a number of frames, similar to cfi and rci.

In practice i'm saing that adding LoadCustomCif() in ImageReader should be ok to import textures as name.cfa_0-frame.png, as opposed to create another import system for these files.

If you don't know what i'm talking about, refer to [this](http://www.dfworkshop.net/projects/daggerfall-unity/modding/textures/).

**Comment by ajrb** [comment]
Thanks, I get what you mean now. Replacements don't need to follow the same format. Makes total sense, thank you for pointing that out.

**Pull request merged**
