### PR TITLE
Spell costs code refinement

### PR DESCRIPTION
**Pull request by ifkopifko**
It will spit out correct costs once offsetGold values are corrected. That is planned for the next pull request.

### CODE REVIEW

**Comment by Interkarma** [comment]
Welcome, and thank you for the refinements! 👍 

I'll leave this PR open until you have parity with the current output. Just add your offsetGold value corrections to this PR and I'll be able to review the whole thing in one hit when ready.

**Comment by Interkarma** [comment]
Thank you! I'll merge this now and let you know if any troubles. Thank for the help with this, not just here but with the formulas as well. :)

**Comment by Interkarma** [comment]
Just a heads up, the new formula is no longer in parity with classic. It seems to have problems with Magnitude-only effects (e.g. Drain Endurance) and Duration+Chance effects (e.g. Paralyze). My old formula was also able to handle these cases with classic parity.

My testing process is to load up the same character with 50 in all magic skills in both classic and DFU, then spin up all kinds of wild combinations in spellmaker in both versions and to make sure they come out the same.

**Comment by ifkopifko** [comment]
Will look into it and come up with a fix.

**Comment by Interkarma** [comment]
> Will look into it and come up with a fix.

It's all good, working OK now. I edited my earlier comment. Not sure what I did wrong in my earlier tests. I'm pretty much running on fume tonight, so mistake is likely mine. I'll try again when less tired and let you know if any more problems. :)

**Pull request merged**
