### PR TITLE
Implement classic stock for private property

### PR DESCRIPTION
**Pull request by Allofich**
Also has minor cleanup to store shelf stock code.

### CODE REVIEW

**Comment by Interkarma** [comment]
I've decided you must be some kind of wizard. :) I like how you've matched the interior furniture types by building type. Is this something else you've worked out from classic disassembly?

**Comment by ajrb** [comment]
Needing the model Id means it will need to be stored with the container since I'm moving stocking back to first activation. Probably toss it in textureRecord field or something.

**Comment by Allofich** [comment]
You mean used the building type as the index? Yes that's how the original is doing it. Doing it the same way allowed keeping the code fairly compact.

**Comment by Interkarma** [comment]
Yep. I assumed it must have come from classic by how specifically it was constructed. Nice work!

**Pull request merged**
