### PR TITLE
Action component for flat->3d object

### PR DESCRIPTION
**Pull request by TheLacus**
I moved my code in AddFlat() and hid the quest part under an if, so action and sound are applied in the same way for vanilla and custom. Let me know if you have other preferences.

### CODE REVIEW

**Comment by Interkarma** [comment]
Hey mate. :)

This one looks like it will break the quest handling of NPC if billboard if replaced. The SpecialNPCClickHandler and StaticNPC components still need to be attached to the replacement GameObject if this is an NPC. These components do not use the Billboard at all and are essential for Quest system to operate on those objects. It's OK to replace GameObject with something other than a Billboard - but the StaticNPC and SpecialNPCClickHandler still need to be assigned.

Here's the general process:

* Use obj.Resources.FlatResource to determine if this is an NPC.
* Inject either standard Billboard or replacement GameObject.
* If this is an NPC, assign StaticNPC (always) and SpecialNPCClickHandler (for special named NPCs). I'll probably get rid of the latter at some point now I'm more comfortable with things. It's a legacy from an earlier direction.

I'm going to merge this one and make the necessary changes quickly so the quest scripts still get attached to replacement GameObject. Can you confirm if replacement GameObject is always given a trigger collider? This is necessary for player clicks on object to be captured.

Cheers!

**Comment by Interkarma** [comment]
OK, reworked now. Change should support either original billboard or replacement, and still add the required NPC quest stuff to either one. As long as replacement GameObject has a nice trigger collider, NPC object should OK in both cases.

Let me know if any problems, I'm happy to try and help how I can. :)

**Comment by Interkarma** [comment]
Cleaned this up a little more. The billboard is now only added if ImportCustomFlatGameobject() returns null. I've completely decoupled NPC check and factionID from billboard.

**Comment by TheLacus** [comment]
Hey, thank you for everything!

> Can you confirm if replacement GameObject is always given a trigger collider? This is necessary for player clicks on object to be captured.

Adding a BoxCollider with `isTrigger = true` will accomplish or there is something more specific to take care?

**Comment by Interkarma** [comment]
That should do it! :)

**Pull request merged**
