### PR TITLE
Add classic interaction mode icons as option

### PR DESCRIPTION
**Pull request by ajrb**

### CODE REVIEW

**Comment by Interkarma** [comment]
Cheers! Will get this merged to master shortly.

**Comment by Interkarma** [comment]
Hazelnut, would you be happy to make classic icons the default setting? A quick sample on Twitter shows a definite preference for classic. And after more playtesting the classic icons are easier to parse over a greater range of lighting conditions. It's easy for the minimal icons to become lost in gray cobblestone in towns, for example.

I'll leave final decision to you though as this one is your feature. :)

**Comment by ajrb** [comment]
Quite  low sample size of people who have not tried it in game yet. I'd like to leave it as it is and poll forumites in a few weeks if that's ok. I think people are more likely to bother to switch to classic to see them which is why I went for this default.

**Comment by Interkarma** [comment]
That's fine mate. Final choice will be yours, as mentioned.

**Pull request merged**
