### PR TITLE
Fixes for DFU 0.10.8

### LINKED ISSUE #1579: Bank - Cannot open the buy ship menu specifically when running game through Unity
**Description**
After exiting Privateer's Hold and getting to the Bank in the city of Daggerfall, it is not possible to open the window used to display and purchase ships. This seems to only happen when running the startup scene through Unity itself and not when playing the game as normally installed, and if trying to buy a ship in a non-port town, it will still pop up the message letting the player know the town they're trying to buy a ship in isn't a port town.

**Steps to reproduce the behavior:**
1. Run DaggerfallUnityStartup scene through the proper version of Unity for this project
2. Go to Bank of Daggerfall within the city of Daggerfall
3. Talk to the banker, select Banking
4. Attempt to select the Buy option for the ship
5. Error output will post to console and the Buy window will not open

**Expected behavior**
I expected to have the Buy window pop up since Daggerfall is recognized by the game as a port town, so I could preview the ships and choose to purchase one.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Version: At the time of this writing, the current clone of the repository.

**Additional context**
I nabbed the error it gave me when I clicked the Buy button, it did not crash the game or soft lock it, I was able to play normally, aside from not being able to buy a ship. The error is below:

`MissingMethodException: No constructor found for DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallBankPurchasePopUp::.ctor(DaggerfallWorkshop.Game.UserInterface.UserInterfaceManager, DaggerfallWorkshop.Game.UserInterface.DaggerfallBankingWindow)
System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:319)
System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Activator.cs:268)`

I will do my best to provide any extra information as required, I'm new with working with Unity and I was just trying to get a character up and running while setting up a dev environment. If there is any extra information I could give that would help, I will do my best to provide it.

### PR DESCRIPTION
**Pull request by ajrb**
Fix identify spell trade window construction call
Fix ship purchase popup window (fixes #1579)
Fix gold rewards for non-guild NPCs with faction ids - hopefully this will fix the 1gp bug, but I don't have a save to test this with

### CODE REVIEW

**Comment by Interkarma** [comment]
You're a legend. Thank you for these. :)

**Comment by petchema** [comment]
> Fix gold rewards for non-guild NPCs with faction ids - hopefully this will fix the 1gp bug, but I don't have a save to test this with

Well, it still happens in 0.10.11; Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2916#p33737

**Comment by ajrb** [comment]
Yes I am aware. Am being a bit lazy, but since I don't think it's enough to justify another build I will fix it later on.

**Comment by Interkarma** [comment]
Is there a reference somewhere that faction should be factored into gold rewards? I think this is one of Allofich's notes, so I'd trust it at face value, but a source would be nice.

But guys, I'm getting a lot of negative feedback on this one. Please consider that I'm the one people send nasty emails to when they're pissed off at something in the game. It might seem like a small issue, but it throws out the feeling of reward and satisfaction. This bug needs some priority.

I'm not sure this change adds anything over the original behaviour. It's more complex and error prone, fixing something that nobody was complaining about in the first place. I'm strongly inclined to.roll back change completely in next builds.

**Comment by ajrb** [comment]
It will be fixed very soon, sorry been a little preoccupied with the mod enhancements and wanted to get that stuff finished. I think I know what the issue is, but need to validate it.

**Comment by ajrb** [comment]
Sorry I rushed the fix before. Have submitted a proper fix now, but I hope someone else will test it to check. I also checked the FG quest rewards and how they matched classic. Before the changes made to follow Allofich's comments low ranks were getting more than they should and conversely higher ranks less. A rank 1 char getting the wild animal quest is now more in the ball park of classic offerings. (since there's a random element the exact values cannot be directly compared)

**Pull request merged**
