### PR TITLE
DaggerfallTilemapTextureArray.shader cleanups

### PR DESCRIPTION
**Pull request by petchema**
(patch on top of #1350 )

Trying (unsuccessfully) to fix seams problem, I did lot of small cleanups on shader code:
    
- Remove commented code (that's what versioning is for);
- Added TEXCOORDn annotations on Input
- used UNITY_SAMPLE_TEX2DARRAY_SAMPLER_LOD to share SamplerState between albedo and normal texture lookups
- added inline annotation to GetMipLevel (but I suppose the compiler must have guessed that much already)
- replaced fmod(x, 1.0) with frac(x)
- replaced tile rotation branching with matrices. I could have replaced matrix product and vector addition with just a matrix product, but I would have to promote matrix to float3x3 because OpenGL ES 2.0 doesn't support non-square matrices:
    
      static float3x3 rotations[4] = {
          float3x3(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0),
          float3x3(0.0, 1.0, 0.0, -1.0, 0.0, 1.0, 0.0, 0.0, 0.0),
          float3x3(-1.0, 0.0, 1.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0),
          float3x3(0.0, -1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0)
      };
    
      float2 uv = mul(rotations[index % 4], float3(frac(unwrappedUV), 1.0));
    
With all those modifications I have seen no change in FPS on my rig, maybe they're better tools to measure shaders performance? Maybe it's simply irrrelevant

### CODE REVIEW

**Comment by ajrb** [comment]
Any chance these changes will remove the lines seen with non-nvidia gfx hardware?

**Comment by petchema** [comment]
I don't think this PR will change shader behavior; Stuff like TEXCOORDn annotations could potentially help with compatibility, but I doubt it'll do anything in this specific case. I should mention I have no hardware to test this hypothesis; All I have is a very old AMD card that features seams, but I don't know how representative it is.
I already mentioned the best lead I have in the forums here: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1464&p=26906#p26906
That is, an issue with the use of fmod: https://stackoverflow.com/questions/14737910/cg-repeating-a-texture-using-fmod-causes-aliasing
and a workaround that only works with the card I mentioned above...

**Comment by Interkarma** [comment]
Thank you for cleanup! :)

**Comment by ajrb** [comment]
That's fair enough - TBH I'm just glad someone is looking and understanding them.

**Comment by Nystul-the-Magician** [comment]
> With all those modifications I have seen no change in FPS on my rig, maybe they're better tools to measure shaders performance? Maybe it's simply irrrelevant
most likely shader compiler optimized those code parts anyway - those compilers are pretty good these days

**Comment by petchema** [comment]
> other possibility is that this shader is not computation bound but memory bound

Yes, I read stuff like that. This shader is so relatively simple that it's probably memory bound.
That's what my "Maybe it's simply irrrelevant" covered...

**Comment by Nystul-the-Magician** [comment]
nevertheless your changes make the code cleaner imo, so thumbs up

**Pull request merged**
