### PR TITLE
Micro map settings revision 7/5/2022

### PR DESCRIPTION
**Pull request by magicono43**
This is a revised version of this PR from a few days ago. https://github.com/Interkarma/daggerfall-unity/pull/2374

### CODE REVIEW

**Comment by magicono43** [comment]
How It Looks In Accessibility Tab:
Capture1

Without Setting Enabled:
Capture2

With Enabled Default:
Capture3

Custom Color Options:
Capture4

With Custom Color Options:
Capture5

**Comment by Interkarma** [comment]
Looks good! Unfortunately I've already cooked the builds for 0.14.1. I'll make sure this goes into 0.14.2 though. It will be a short turnaround time (about 1 week again).

**Comment by Interkarma** [comment]
Hmm, just realised you've revised the settings as well. That's no problems - what I'll do is leave this out of patch notes for now, and instead feature in the notes for 0.14.2 in another week once the full feature is merged.

**Comment by magicono43** [comment]
> Looks good! Unfortunately I've already cooked the builds for 0.14.1. I'll make sure this goes into 0.14.2 though. It will be a short turnaround time (about 1 week again).
> 
> Hmm, just realised you've revised the settings as well. That's no problems - what I'll do is leave this out of patch notes for now, and instead feature in the notes for 0.14.2 in another week once the full feature is merged.

No problem, was sort of really late last night (for my side of the world) when I pushed this out and figured it would probably not make it for 0.14.1, lol.

**Comment by Interkarma** [comment]
I have to redo builds because I missed something in the Mac bright UI fixes. This gives me a chance to merge this for 0.14.1 after all. :)

**Comment by magicono43** [comment]
Awesome, looking forward to seeing it in the next build then, thanks!

**Pull request merged**
