### PR TITLE
Scene cache implementation to handle stateful game objects - finished

### PR DESCRIPTION
**Pull request by ajrb**
This is all finished up now and house containers are dealt with correctly. I also added a special case for travelling to / from your ship so the scene cache is not cleared. This means when you pop onto your ship and return, the town will be as you left it. Sort of simulates the ship being docked at the port, although works for non-port towns as a player convenience.

### CODE REVIEW

**Comment by ajrb** [comment]
BTW, don't try to merge this into your sceneCache branch. You'll need to create a fresh branch from master and have me target the PR at that. If you really don't want to merge into master before trying it again.

**Comment by ajrb** [comment]
I've added a price list for ships tonight - without 3d model display, will submit another PR for that in case you want to leave it out of 0.4 final build

**Comment by Interkarma** [comment]
This is awesome, thank you! Will merge this now and get it into master very soon, along with new builds.

Happy for you to push the additional ship stuff. I'm not too worried about that as it shouldn't affect the world exploration or questing side of things even it does need more work later.

**Comment by ajrb** [comment]
Okay as soon as you merge this into master I will submit the ship purchase PR. Will be around for next couple of hours. :-)

**Comment by Interkarma** [comment]
> BTW, don't try to merge this into your sceneCache branch. You'll need to create a fresh branch from master and have me target the PR at that. If you really don't want to merge into master before trying it again.

I'm sorry, I missed this earlier comment. Have already merged this into my sceneCache branch for testing on my end.

I'll create a new branch from master called sceneCache-Final for you to send final to and delete my copy of the sceneCache branch when I'm done testing. Is that suitable?

**Comment by ajrb** [comment]
I don't think you realised but it's already in master. Just test master, and try not to curse me for confusing you. I didn't have another branch to target and if I targetted the old sceneCache branch it could easily have messed up unless you deleted and recreated it first. Sorry.

**Comment by Interkarma** [comment]
Ah! I'm sorry, I see what's happened now. I had assumed you sent those updates back to the sceneCache branch for me to test, but they were targeted to master. I blindly hit merge thinking I was just merging to a branch.

Haha, my bad. Haven't been awake long sorry mate. I'll delete my sceneCache branch then. :)

**Comment by ajrb** [comment]
Phew, glad we're on same page now. :)

**Pull request merged**
