### PR TITLE
fix background behind some messageboxen

### PR DESCRIPTION
**Pull request by petchema**
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2126

Git bisect points at commit 445a9a89

There's a lot of ways to create DaggerfallMessageBox objects, maybe there's another, existing,way that I missed...

### CODE REVIEW

**Comment by ajrb** [comment]
@Interkarma FYI I have added a fix for this into my fixes PR. Up to you if you'd prefer a new shortcut method for tokens as @petchema has done here.

**Comment by Baljak** [comment]
@petchema Sorry I just saw your PR and I've also fixed this in the same way in my NPC greetings update.
Since I've also done a lot of work in TalkManager as well and reworked the way this part of the code is called, I think it would be best to close the PR to avoid any merge conflicts.
@ajrb Could you also update your own PR to remove this part of the fix as well?

**Comment by df-ferital** [comment]
@petchema Sorry I just saw your PR and I've also fixed this in the same way in my NPC greetings update.
Since I've also done a lot of work in TalkManager as well and reworked the way this part of the code is called, I think it would be best to close the PR to avoid any merge conflicts.
@ajrb Could you also update your own PR to remove this part of the fix as well?

**Comment by petchema** [comment]
@Interkarma I'm closing this one then

**Pull request closed without merging**
