### PR TITLE
World data and quest action development for mods

### PR DESCRIPTION
**Pull request by ajrb**
Whew, this is a big one. I apologise in advance for the amount of effort this will take to review and check. It's going to allow some pretty cool stuff from modders though. I've been developing a new quest for the roleplay mod which has multiple paths, new npcs, new location, and dynamically changes the world providing a new service to successful players. These are all the changes I needed in core to make it possible. If anyone wants to test these changes with the new quest, let me know.

So here's a rundown of what's in this PR:

- Ability to override RMB blocks including ground data.
- World data variant system allowing dynamic changes to the game world. Variants can also be specific to a location, so just a single building in the whole world can be targetted for the changes.
- Allow multiple quest markers to be used when placing npcs and foes from quest scripts.
- Add new quest actions: worldupdate, clickedfoe (credit: DFIronman), enemies, killfoe, paymoney, journalnote.
- Allow new locations to be targetted as permanent quest sites.
- Enable adding data to quest tables from mods.
- Allow new individual npc's to use (almost) all of the faces in the game.
- Add a player lastname macro.
- Enable mods to add new merchant services.
- Various bugfixes.

### CODE REVIEW

**Comment by Interkarma** [comment]
I'd love some help testing this one @TheLacus, @petchema, @numidium, @JayH2971, @Nystul-the-Magician, and any others interested. The more eyes on it before merge, the more likely we are to catch any issues. We have different areas of interest and expertise, and we could all spot something that I might miss.

Thank you @ajrb for the PR and everyone who can help test. :)

**Comment by JayH2971** [comment]
Would anyone be able to make a Linux build with this PR included? I can't make builds myself and I think this is important to test. (I'm still not free from stomach flu so this isn't urgent, but I'm happy to get involved when I can.)

**Comment by Interkarma** [comment]
@JayH2971 Can do Jay. I'll PM you a link within next 24 hours. Thank you for help. :)

**Comment by Interkarma** [comment]
I have elevated this PR to a branch of it's own. Merging changes to branch where we can continue work on it.

**Comment by Nystul-the-Magician** [comment]
I plan to take a look as well soon ;)

**Comment by JayH2971** [comment]
So far I've done the following quests and picked up/delivered/dropped (where applicable) the quest item, and things have all gone well:
MG Retrieve an Ingredient
MG Mummy Wrappings
MG Research Notes
MG Guard the Guild
TG A Hot Stone
TG Drugs Delivery
TG A Treasured Potion
Merchant The Courier

The Courier was the one that I thought could cause problems since I surrendered the item to the thief and then killed to get it back. But the item ID persisted fine; the turn-in was a success.

**Comment by Nystul-the-Magician** [comment]
I tested a bit - so far things are working
I might though have found an unrelated bug (residences marked on map get cleared once you open the quest log - not sure if this is related to the fact that it is a quest that contains the named residence in the quest text - can one of you try to reproduce this please)

**Comment by Interkarma** [comment]
@ajrb I'm going to merge this and drop builds with this change over weekend. Just letting you know in case there are some last-minute changes you need to make. :)

**Comment by ajrb** [comment]
@Interkarma Great, sooner the better due to my upcoming lack of time. I have some this weekend and maybe a little in the coming week. In case there are issues.

**Pull request merged**
