### PR TITLE
fog color in interiors and dungeons is now black

### PR DESCRIPTION
**Pull request by Nystul-the-Magician**

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
btw, we could maybe go with higher density fog values for dungeons - but I did not dare to change it for the moment since I don't want to break other stuff that I did not have time to test (like darker dungeons feature)
but a DungeonFogSettings with density e.g. 0.05 looks better than the current 0.005 in my opinion - feel free to try and fine tune - the same for InteriorFogSettings (used for building interiors)

**Comment by Interkarma** [comment]
Thanks for the fix! By the way, it looks like foggy weather can appear in dungeons as well.

https://forums.dfworkshop.net/viewtopic.php?f=4&t=37&p=19399#p19377

Bug or not, that does look kind of incredible. I see your point about higher fog density in dungeons. :)

Maybe "foggy dungeons" is something we can expose as an option with some randomness to density (seeded by mapid perhaps so it's the same each time player enters dungeons).

**Comment by Nystul-the-Magician** [comment]
previous pr fixed foggy weather in dungeons ;)

**Comment by Interkarma** [comment]
>previous pr fixed foggy weather in dungeons ;)

Ah, thank you! Sorry I missed that, I haven't jumped into review mode for this round of PRs yet. :)

We can worry about intentionally foggy dungeons later in any case. 👍

**Pull request merged**
