### PR TITLE
[Joystick Controls] Added bindings for UI mouse clicks and inversions of axes

### PR DESCRIPTION
**Pull request by jefetienne**
Added new bindings to the game that for now can be modified in the Keybinds.txt file:
- UI mouse clicks, left-click (JoystickButton0, or 'A' by default) and right-click (JoystickButton1, or 'B by default'). I did not add the middle click to have a default since I don't believe it's used anywhere in the game, correct me if I am wrong.
- Inversions of movement (Axis1 horizontal, Axis2 vertical by default) and camera (Axis4 horizontal, Axis5 vertical by default), all "False" by default

These, along with the actual axes, will all be rebindable in the upcoming UI for the joystick controls window, once this and #1816 get merged, either order.

### CODE REVIEW

**Comment by Interkarma** [comment]
This one might need to be rebased, conflicts with current master now #1816 merged.

**Comment by jefetienne** [comment]
Ugh, this is annoying. Sorry, I'll just make a new PR.

**Comment by Interkarma** [comment]
Sorry @jefetienne :(

**Comment by jefetienne** [comment]
> Sorry @jefetienne :(

It's fine! I had some confusion after rebasing when it told me my branches diverted and it said to use `git pull` to merge the remote branch. I believe I should've just called `git pull --rebase` again.

**Pull request closed without merging**
