### PR TITLE
Enable custom items to be added by mods

### PR DESCRIPTION
**Pull request by ajrb**
Builds on the rudimentary support I added for the locator device 2 years ago.

Now uses the item templates file and defines a template index which for custom items is used for the group index as well.

Regarding paperdoll items, Weapons and armor are fully functional and tested. Clothing may need a bit more work which I will look at soon but I wanted to get this on the list of PRs so people can start to review the changes. Corresponding changes can be found in my Archs mod and Loot Realism on this branch: https://github.com/ajrb/dfunity-mods/tree/moderateWeaponMaterials

Loot realism now adds 2 new weapons: Archers Axe and Light Flail, and also a new lighter set of mail armor allowing players who can't wear plate to get high level material armor pieces.

NOTE: This PR builds on #1747 and as such contains all of those changes as well. (first 9 commits) Either review & merge this one and I'll close that one, or review & merge #1747 first and then this should lose all those changes to allow it to be reviewed separately.

### CODE REVIEW

**Comment by ajrb** [comment]
I have absolutely no idea wht GitHub has ended up duplicating other peoples changes in this PR just because I merged the master into my branch and resolved the conflict. This drives me nuts sometimes - really wastes time

**Comment by ajrb** [comment]
New PR #1762 is submitted with a fixed branch. Wish I knew what I do wrong when this happens..

**Comment by TheLacus** [comment]
You want to _rebase_ your branch on top of master, not _merge_ the new additions to your branch. Next time you can use the following: `git pull --rebase upstream master`.

**Comment by ajrb** [comment]
Ah, I rebase my master and then rebase my branch to that, then GitHub seems to merge the remote to my local clone and screw everything up for me. Is your suggestion the same as:

git fetch upstream
git rebase upstream/master

Or am I mis-understanding which part of the process you mean I should use the command you gave?

**Comment by TheLacus** [comment]
You stated "I merged the master into my branch" so i thought that was issue. There is [a difference](https://gitolite.com/git-pull--rebase) between _rebase_ and _pull --rebase_ but i don't think it would make any difference in this case.

I never had any issue with _pull --rebase_, so i don't know what happened here...

**Comment by ajrb** [comment]
Thanks for the advice, so everything worked fine using the command you gave me above, but as far as I can tell it was no different than doing fetch and rebase like I normally do. However I noticed that you had force pushed to update your mobs PR so thought I'd try that on cmd line and that worked fine.

I think the issue has been that when I've been pushing the updated local repo to remote github messes everything up. Good to know how to avoid this now. :)

**Pull request closed without merging**
