### PR TITLE
Quests: minor fixes

### PR DESCRIPTION
**Pull request by KirillSmirnov**
This PR fixes gender-related discrepancies between QRC and QBN blocks and updates quests status.

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
regarding A0C00Y11 and A0C00Y12 - npcs not showing up on where is -> person is working as intended. Check the quest in vanilla df, e.g.:
A0C00Y11:
`dialog link for person _healer_ item talisman` hides the npc
will be only available when pc gets right answer when asking about cousin

**Comment by KirillSmirnov** [comment]
@Nystul-the-Magician That's strange. I have the following experience:
A0C00Y11:
1) started the quest and got some money
2) traveled to ___cousin_
3) asked about _cousin_ there. People did not reveal __cousin_ home, but told me about _healer_ instead.
4) asked about _healer_ and people revealed his town ___healer_
5) traveled to ___healer_ town and stuck :-( I cannot find __healer_ home. "Where is..." is empty and "Tell me about" is still the same.

A0C00Y12:
Almost completed entire quest but failed to find _giver_ to get reward - where is he? Specifically, I got the quest from Gwynyvyra Yeomton, but I cannot ask about her. The only available person to ask about is Andynak Yeomton.

Also, in this case _giver_ is a female, ignoring stanza in A0C00Y12.txt:
Person _giver_ group Questor male

Build #113 20-May-18

**Comment by Nystul-the-Magician** [comment]
will take a look and at A0C00Y11 quest. Not sure what is goind wrong there

**Comment by Nystul-the-Magician** [comment]
ok, I found something that does not work like intended:
when travelling to healer town method Person.GetAssignedPlaceSymbol() returns null...
maybe Iterkarma can help with this.
where does the quest code specify that healer is in remote town? can't find anything and wondering how it even works out to place it in a remote town

**Comment by Nystul-the-Magician** [comment]
regarding observation about questor in A0C00Y12 - yes there is also a problem but also not a problem of dialog system but person resource as well:
When getting the quest from female person (in my test: "Evelyn Gaerston") the entry in the "where is"->"person" section becomes "Tristan Gaerston" because person resource class returns this a questor's name

**Comment by Nystul-the-Magician** [comment]
I will create a separate bug report for both quests

**Pull request merged**
