### PR TITLE
Implement soulgem selling service

### PR DESCRIPTION
**Pull request by ajrb**
Addresses issue #1377 

Should be checked for DB and for Temple of Arkay by bug author @Hellmasker10.

### CODE REVIEW

**Comment by ajrb** [comment]
Also noticed the tooltip for the dungeon access was not updated to match the changed implementation so corrected it from 10 -> 5m

**Comment by Interkarma** [comment]
Thank you mate! :)

**Comment by petchema** [comment]
Vondur / Adventure Art received a "Guild service not yet implemented" message trying to buy soulgems from the Dark Brotherhood:
https://www.youtube.com/watch?v=hEjqD5blf88&t=287

**Comment by Interkarma** [comment]
>(0.10.2)

That's likely the reason. This feature was merged on 01-Aug and is only present in 0.10.4 and later.

**Pull request merged**
