### PR TITLE
fix for github issue 1381

### PR DESCRIPTION
**Pull request by Nystul-the-Magician**
(https://github.com/Interkarma/daggerfall-unity/issues/1381)

public function now only calls private function
all resolving is done there
if there is a building override name this name is taken otherwise further building name resolving is done

### CODE REVIEW

**Comment by Nystul-the-Magician** [comment]
need to fix a bit more (residence names don't show up right now)

**Comment by Nystul-the-Magician** [comment]
I will have to make some changes to building discovery code to support "reveal on info click without pc having learned from townsfolk" and getting permanently marked on map as well
for now I decided to info click to behave like this:
- "residence" if residence was not marked on map by npcs
- named residence if residence was marked on map by npcs
so pc can not reveal for now by spam clicking all buildings

this is because the "get discovery code" will return a flag on finding building discovery but this needs to be different for info clicks than when automap uses the code, otherwise automap would always reveal all residences as named residences
I will put some time and effort into this issues next week
for now it should do as described above

**Comment by Interkarma** [comment]
>I will have to make some changes to building discovery code to support "reveal on info click without pc having learned from townsfolk" and getting permanently marked on map as well but not accidently revealed when building map nameplates

Is this related to buildings involved in a quest?

**Comment by Interkarma** [comment]
Just FYI, this also fixes the lockpicking regression issue #1373 that was also caused by the earlier change to discovery. My apologies for not spotting these two issues before merging, I was very time poor leading up to alpha. Happy to spend bit more time with you on this one. Between you, me, and @ajrb I'm sure we'll smash it. :)

**Comment by Nystul-the-Magician** [comment]
> 
> 
> > I will have to make some changes to building discovery code to support "reveal on info click without pc having learned from townsfolk" and getting permanently marked on map as well but not accidently revealed when building map nameplates
> 
> Is this related to buildings involved in a quest?

yes, one aspect of it is about residences and if pc got them marked on map by npcs (override name is alone is not enough for this since it is available from quest start, so additional handling code that calls into talk manager checks if a npc marked the residence on the map or not for now).
all those "problems" and issues with nameplates sometimes not showing up on map is related to the different systems using the building discovery code (but need them to behave slightly different, e.g. automap nameplate generation needs to get building names but not reveal them but instead info clicks should reveal them) - the goal from my side is to have one function to handle all those cases but maybe with flags to control behavior (so we don't have duplicate code for building discovery name handling) - in the past we had 2 functions and e.g. player house naming would only be returned by one of the 2...

**Comment by Interkarma** [comment]
Thank you, take your time. This end of the project is all about making things incrementally better. The mad rush to implement systems is over now.

**Comment by Nystul-the-Magician** [comment]
working on this now - looking good - will make a new pull request when done - so no hurry to merge this one ;) will close this one when I am finished ;)

**Pull request closed without merging**
