### PR TITLE
Get door lock value like classic

### PR DESCRIPTION
**Pull request by Allofich**
Gets the lock value for doors in the same manner as classic.

For regular locks the value will be the same, but apparently magical doors can have a few different values, which wouldn't be correct before this PR. Maybe those values matter when using lock-opening spells.

### CODE REVIEW

**Comment by Allofich** [comment]
Fixed a problem with the Castle Daggerfall entrance doors. They were being found as a "DaggerfallActionDoorSpecial" and not being unlocked, so if you closed them they locked again, and you could lock yourself in the castle.

I don't know much about the "DaggerfallActionDoorSpecial" so this fix (checking for a regular door first) might interfere with what you used the special door for.

**Comment by Allofich** [comment]
Although I haven't seen a problem with the CloseDoor action (where is it used?) I imagine it would have the same problem of being detected as a special door and not being locked, so I put in the same fix there.

**Comment by Interkarma** [comment]
Interesting, thank you for the fix. The "DaggerfallActionDoorSpecial" component is for doors that are opened by an action, but do not otherwise have the DaggerfallActionDoor component attached. A good example are false bits of pillars in Lysandus' Tomb which are not actually doors but still need to receive an "open" action. I created a new component just for these objects rather than refactor the entire door/lock setup. I'll need to see why the "DaggerfallActionDoorSpecial" was applied to these doors, that will be an error of mine.

It looks like your fix should do the job. Will test and let you know if any issues.

**Comment by Interkarma** [comment]
This one breaks the "DaggerfallActionDoorSpecial" usage, unfortunately. Rather than revert, I'll see if I can resolve issue from PR.

**Pull request merged**
