### PR TITLE
Changes to support class overrides for some component classes.

### PR DESCRIPTION
**Pull request by DunnyOfPenwick**
Changing 'private' variables/methods to 'protected', making some methods 'virtual'.

### CODE REVIEW

**Comment by DunnyOfPenwick** [comment]
I screwed up and neglected to refresh the code base before issuing this pr, resulting in an additional branch merge.
Do I need to redo this pr?

**Comment by jefetienne** [comment]
> I screwed up and neglected to refresh the code base before issuing this pr, resulting in an additional branch merge. Do I need to redo this pr?

The cleanest way, you can do a `git rebase <your_remote_name_for_interkarma/daggerfall-unity> master` to try and place all your commits on top of the latest commit of the master branch. It rewrites the git history for each of your commits - if there are any conflicts while it iterates through each commi,t it will stop you to try and fix it. Once you do,  do `git rebase --continue`. If you feel like you messed up, you can do `git rebase --abort` and try again.

**Comment by Interkarma** [comment]
Hi :) responding your email here. The below forum topic has more information about where I'm at with Daggerfall Unity. To summarise: I'm no longer merging PRs that don't fix an accepted issue and will be placing DFU behind me after 1.0. My intent is to wrap up involvement with DFU in the next 6-8 weeks.

https://forums.dfworkshop.net/viewtopic.php?t=6018

I will make exceptions for very simple changes, but your PR opens up many private fields. Some of which are part of internal flow of state, and some are cached references or enemy properties you can already get elsewhere. Is it possible to simplify PR?

I don't want to be an obstacle, and I'll try and work with you to get this merged. You submitted this only a couple days before the cut-off and I'm usually fine with just opening fields up from private to protected. But this one does feel like a very broad brush instead of being targeted to exact needs.

BTW, there's also a minor conflict in this PR now. Nothing serious and can be easily corrected on next draft.

**Comment by DunnyOfPenwick** [comment]
When I originally made the variable/method scoping changes, I figured I might as well change the scoping of all the variables/methods 'just in case'.

I probably only really needed to modify a fraction of that to accomplish my goals.

On the one hand, when v1 comes out it will likely attract a good bit of new attention, and it would be nice if there were as many rich features as possible to give players a good impression. On the other hand, the number of possible features that can be added are effectively endless, which traps you.

If making more targeted changes would help, I'd be happy to do it.
Should I proceed with making a new PR with targeted changes? Or would you prefer I just forget about it until some time after 1.0 comes out?

------- Original Message -------

**Comment by jefetienne** [comment]
If you need to modify non-public variables in the meantime, you can use reflection to modify the fields you need.

https://stackoverflow.com/a/12994027

**Comment by KABoissonneault** [comment]
I don't recommend mods rely on private symbols unless they're prepared for updates to break their mods. Sure, it works, but DFU shouldn't have to guarantee the stability of anything private.

**Comment by DunnyOfPenwick** [comment]
I will be closing this pull request in the near future.

I originally intended to add support for a couple of my mods without modifying existing logic, but now intend to rewrite code for smoother codebase interplay.

A 2-line change to FPSWeapon.cs should be sufficient to enable my First-Person-Lighting mod:
1) a new public 'Tint' property
2) an additional argument (Tint) added to the end of the DrawTextureWithTexCoords call in the OnGUI method.

My Monster-University mod would require significantly more logic changes to multiple classes.

I had inadvertently added an additional fix in this pull request related to DaggerfallEffectSettingsEditor.cs.
The background of the effect settings editor window should be dimmed to match the original Daggerfall.
I consider this a visual bug.  It's a one-line fix.

**Comment by DunnyOfPenwick** [comment]
Closing

**Pull request closed without merging**
