### PR TITLE
Quest fix Nov 2019

### PR DESCRIPTION
**Pull request by JayH2971**
Fix text error C0C00Y10

### CODE REVIEW

**Comment by df-ferital** [comment]
There is a problem with your commit, it only adds an empty line.

**Comment by Interkarma** [comment]
> There is a problem with your commit, it only adds an empty line.

This is actually the fix. :) There needs to be whitespace between text blocks and comments or the comment will be included in text block.

**Comment by Interkarma** [comment]
@JayH2971 from the subject of the PR, should I assume that more fixes are incoming?

**Comment by JayH2971** [comment]
I'm sort of leaving it open-ended right now. No guarantees if more come in anytime soon, so don't wait for me.

**Comment by df-ferital** [comment]
> > There is a problem with your commit, it only adds an empty line.
> 
> This is actually the fix. :) There needs to be whitespace between text blocks and comments or the comment will be included in text block.

Sorry I didn't know that :)

**Pull request merged**
