### PR TITLE
Tavern room rental system fully implemented

### PR DESCRIPTION
**Pull request by ajrb**
It works really nicely, hope I've not missed anything.

Hope you don't mind using the serialization object to store these things in player entity. Nothing needs transforming.

### CODE REVIEW

**Comment by Interkarma** [comment]
That was fast! Great stuff. Will get this merged when I can around work today.

**Comment by ajrb** [comment]
I've been really enjoying programming DFU for last couple of weeks, it's all I've wanted to be doing when I have free time. (and even when I don't)  I'm rather binary when it comes to motivation - either full on like this, or off like over xmas. :-)

I wanted there to be a way for players to have persistent dropped loot before having 100k gold to blow on a boat... now there is.

**Comment by Interkarma** [comment]
And I've enjoyed everything you've created. :) I'm much the same with motivation as well. I can either find the headspace or I can't. Here's looking forward to more awesome collaboration in the future.

**Comment by Interkarma** [comment]
This is great! 👍 

Interesting thing - character might not wake up on top of a rest marker inside all taverns. For example Daggerfall/The Rusty Ogre Lodge has a single tavern called The White Goblin. Whenever I rest here, player just wakes up on the same spot they initiated rest. The tavern appears to have rest markers as normal, the code all looks right, and it works everywhere else I've tested so far. Not sure what's going on in the above tavern.

Let me know if you get the same thing.

**Comment by ajrb** [comment]
That's interesting, I will investigate it this evening. Thanks for the report.

**Pull request merged**
