### PR TITLE
remove a missed reference to old interface icons

### PR DESCRIPTION
**Pull request by petchema**
Seen in a stream

### CODE REVIEW

**Comment by Allofich** [comment]
Minor point, but, I think it would be better without "just", as I think that was in contrast to the removed "click until" alternative.

**Comment by petchema** [comment]
I hope it's now good enough... until a total rewrite ;)

**Comment by Allofich** [comment]
I think it's OK.

> until a total rewrite

Personally I like to keep the original text with minimal changes, or at least still have it available somehow.

**Comment by petchema** [comment]
> Personally I like to keep the original text with minimal changes, or at least still have it available somehow.

That's pretty much the definition of what I've done with the tutorial so far: replace now irrelevant (hence confusing) informations with updated ones, keeping changes minimal. And indeed that tutorial may stay around forever as an option for purists.

It's clear however that this tutorial is very far from the state of the art when it comes to ingame help, and not only because of its content; So I was referring to projects like https://forums.dfworkshop.net/viewtopic.php?f=12&t=1372 or https://forums.dfworkshop.net/viewtopic.php?f=12&t=1930 even if what should be done is not precisely defined yet...

**Comment by petchema** [comment]
"Quarter-screen HUD with icons and mouse cursor toggle" https://www.dfworkshop.net/projects/daggerfall-unity/roadmap/

Mmh! So the references to the "old" UI may still be useful later?

**Comment by Interkarma** [comment]
Yeah, I've had a few requests and do plan to add it down the road. It's not that high priority though. I polled on twitter some time back, and the vast majority of users indicated they either don't care or actively dislike the chunky HUD.

**Pull request merged**
