### PR TITLE
Allow to pay fast travel using letters of credit

### PR DESCRIPTION
**Pull request by petchema**
Bug report:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1332&p=15858#p15858

Behavior matches classic Daggerfall.
For improved consistency, money available includes letters of credit,
unlike classic.

### CODE REVIEW

**Comment by ajrb** [comment]
This was pretty much the only reason to keep any gold on you, and I will admit I quite liked having to keep some cash for travelling.

**Comment by petchema** [comment]
I modified the patch to go the logical route rather than match classic Daggerfall exactly.

**Comment by Interkarma** [comment]
Thanks for making change to still require GP for taverns. I've always liked the RP aspect of this. I don't think it's a bad idea for letters of credit to be accepted on ships.

@Allofich @ajrb Are you happy with this change as it stands?

**Comment by ajrb** [comment]
Yep, cool change - thanks for the refinement petchema.

**Comment by Allofich** [comment]
I'm fine with it, I don't have much of an opinion about it.

**Comment by Interkarma** [comment]
Thanks guys. I'll merge this one to 0.6.

**Pull request merged**
