### PR TITLE
Commoner Quests:  errors and inconsistencies in punctuation, grammar, spelling, spacing

### PR DESCRIPTION
**Pull request by bansheexyz**
Notes:
-lots of missing commas or apostrophes that are technically necessary, and many commas where a period should be. Proper punctuation helps readability.
-about 10% of the time, two spaces followed a period. This inconsistency has been removed in favor of one space everywhere. The two-space thing is an old style with monospaced typewriters that has fallen out of favor in modern text.
-ellipses did not have consistent spacing
-there is an awkward lack of contractions, but only in a few instances does it sound so bad that I thought it warranted a change. "It is you!" is one example.
-there are a few macro fixes of %g2 and %g3 being swapped
-I am a strong writer and have a BA in English. Please discuss or post links to grammar articles if you think there is an error here.

### CODE REVIEW

**Comment by bansheexyz** [comment]
Trying to figure out github to make a separate PR for the classiceffects. Did not mean to add that on here.

**Comment by philliprmurphy** [comment]
My only issue is that it is realistic for people to occasionally speak with improper grammar. Just as a random example, you tend to insert "that" into a lot of dialogues where an average English speaker might not bother to say it. "I suppose since you did get that..." was changed to "I suppose that since you did get that..." The structure of the original sentence is more common in everyday speech, at least where I am from, and sounds more natural to me than the wordier revision. Of course, the meaning doesn't really change and I understand why it makes sense to iron out really awkward phrasing, but dialogue changes for purely grammatical correctness don't make much sense to me.

As a quick second example, I see in one instance, you changed "libelous" to "slanderous". While "slanderous" would be the correct word to use in that sentence, I also find it realistic for someone to make that mistake when speaking to someone else.

I'm not really a purist, so it doesn't bother me too much as the meaning is essentially the same, but I know a lot of people would be annoyed by it, so if you ask me, you should separate the changes you made for punctuation, spelling, and consistency reasons from the changes you made for grammatical reasons.

**Comment by bansheexyz** [comment]
Regarding the omission of "that": it's fine to do it in certain places, but not when it sounds bad or creates potential confusion. I'll revert the one in A0C01Y13 after know, but not the one between "suppose since", which to my ear sounds necessary. It's the difference between:

I suppose we can go to the movies. (fine)
I suppose since we have a car, we can go to the movies. (sounds bad)
I suppose that since we have a car, we can go to the movies. (fine)

You can read more about this in the bridge verbs section here: https://www.quickanddirtytips.com/education/grammar/when-to-delete-that

Some grammar errors are fine in dialogue, as long as the character is known the speak like that and it adds some flair to the character. For example, if you've got Farmer Joe saying things like "I ain't got no time but fer the horses," that's fine, and the reader is amused and knows it's improper. The "libel" vs "slander" slip is a common, but less recognizable error that even the reader might make, so readers aren't going to get any gratification from its wrongness the way they did from Farmer Joe. This just isn't the sort of error a writer would intentionally have a character say right off the bat, unless it was followed by another character correcting him or something.

**Comment by tolbell** [comment]
In my opinion, the vast majority of your changes are great, but I also take issue with altering the informal style of certain lines. I feel that this sort of thing belongs in a mod.

In A0C00Y00.txt:
> Hullo there, young %ra. How'd you like to make

was changed to

> Hullo there, young %ra. How would you like to make

People do talk like this. "How'd" meaning "how would" is common slang.

In A0C00Y16.txt:
> _missingperson_? Naw. Haven't

was changed to

> _missingperson_? Nah. Haven't

Again, people do talk like this. It's pretty clear that the writers wanted this line to include "hillbilly" slang.

In A0C00Y16.txt:
> since day before yesterday. You could

was changed to

> since the day before yesterday. You could

Then, in A0C01Y13.txt:
> _giver_ are behind all this!

was changed to

> _giver_ are behind all of this!?

People frequently omit words in casual conversation. To my ear, the original lines sound perfectly natural, given the context. (Except that obviously, I agree with the addition of a question mark to the last line.)

Then there are two changes regarding addition of the word "that," as discussed above.

In A0C00Y16.txt:
> I know it wasn't your fault you were
> unable to find _missingperson_

was changed to

> I know it wasn't your fault that you
> were unable to find _missingperson_

Then, in A0C01Y09.txt:
> Ahem. Well, yes. I suppose since you

was changed to

> Ahem. Well, yes. I suppose that since you

And finally, your example provided above:
> I suppose since we have a car, we can go to the movies. (sounds bad)

Maybe it's a result of growing up in a poorer area, but this sort of slang doesn't sound unnatural to me at all. I understand that it's technically improper, but by changing it, you've made the lines more formal than the writers may have intended.

**Comment by bansheexyz** [comment]
"How'd" is almost always contracted from "how did", yet in this case it means "how would". Unlike other contractions, there's no contextual boundary here, you get halfway through the sentence before realizing you read it wrong. I think even informal speakers realize this, because I usually hear the "woo" preserved as in "howuja like to". "How'd" seems like a terrible phonetic translation of what happens in real speech.

https://english.stackexchange.com/questions/114281/meaning-of-howd-you-know-would-did-or-do

Some of these lesser used spellings just look out of place. Naw looks like "gnaw", so that's one reason to never write it that way, but if you were going to use naw, why immediately follow it with formal styling?

"Naw. Haven't seen %g2 **for** a couple **of** days. Try **asking** _friend3_. %g might know."
could've been:
"Naw. Haven't seen %g2 fer a couple days. Try askin' _friend3_. Reckon %g might know."

Same thing happens with A0C00Y16. Look at the other sentences in that same paragraph. There are opportunities to write consistently by omitting words.

"Thank god someone **has** found me!" vs "Thank god someone found me!"

"**What is** that you say?" vs "What's that you say?"

That's why "all of this" looked right later on the paragraph, because it matches the style that had been established by the character's prior words.

Do you actually think "since day before yesterday" sounds normal? Or the lack of "that" after the word "fault", which isn't even a verb here?

**Comment by tolbell** [comment]
I disagree with the approach of judging lines by whether they "sound normal" or "look out of place" to this or that person. This sort of thing varies so heavily by economic class, region, etc. that it seems like a pointless standard to use.

Re: style consistency - I see your point, and you have personally won me over to those changes. However, I still believe that the original text ought to be preserved, even with inconsistent style. It seems to me (but do correct me if I'm wrong) that Daggerfall Unity aims to enable a purist-friendly experience, which is why I think that significant changes which go beyond fixing objective errors should be in a mod rather than the base package.

**Comment by Arcane21** [comment]
Yeah, given I've tried to fix text for grammatical reasons and gotten shot down on a lot of changes based on my own knowledge of grammar, this sort of thing, outside of grossly wring text that just look wrong by even most basic grammar smell test, it's should otherwise be made a mod.

**Comment by bansheexyz** [comment]
> 
> I disagree with the approach of judging lines by whether they "sound normal" or "look out of place" to this or that person. This sort of thing varies so heavily by economic class, region, etc. that it seems like a pointless standard to use.
> 
It's not a see-saw effect, though. It's not like adding "that" in said places is going to make the sentence sound as bad for you as it did for those affected by its omission. Which means it's safer to include than omit. If my brain hiccups in a certain place after all the reading that I've done my life, something is probably wrong and is going to sound wrong for others.  I'm not sure how sometimes optional conjunctions and prepositions qualify as purity-defiling mods. I consider these extremely minor changes with no impact whatsoever on original content and meaning.

Also notice that no one complained about the robotic "It is you!" being altered. We all know that there's a 0% chance a speaker would not contract here. Yet it hits harder than most spelling and grammar errors.

**Comment by Arcane21** [comment]
> Those weren't grammatical fixes, though. The Diablo series has a sword called "The Grandfather". >Are you saying "The" is grammatically incorrect for unique items?

In that case there was precedent for the name. There is a sword in the Gothic series called "El Bastardo" (The Bastard) because it was deliberately given such a name and no lore contradicted it.

In the event I tried to change names, it was to match up with artifact names from later games to Daggerfall's names for consistency. I was told not to bother and complied, and while I still believe such renames were appropriate, I'd rather make them an external mod instead of part of the core engine because I'd rather avoid conflict with those who feel such is less a fix and more a personal preference choice.

**Comment by tolbell** [comment]
> It's not like adding "that" in said places is going to make the sentence sound as bad for you as it did for those affected by its omission.

How do you know? What data have you looked at to determine how "bad" each sentence sounds to each party involved? Again, is this really the standard that ought to be used to decide whether a change should make the cut? If so, shouldn't you put out a poll to all potential readers to see which version of each line they prefer, and how strongly they feel about it? A pull request on GitHub isn't going to get nearly enough attention....

> If my brain hiccups in a certain place after all the reading that I've done my life, something is probably wrong and is going to sound wrong for others.

Or, it could be that all that reading has made you extra-sensitive to these sorts of things. I see nothing to be gained by going back and forth repeating, "Well, it doesn't sound wrong to _me_...."

> I'm not sure how sometimes optional conjunctions and prepositions qualify as purity-defiling mods. I consider these extremely minor changes with no impact whatsoever on original content and meaning.

If the original content and meaning have been left completely unimpacted, what need is there for these changes? Clearly, you think that these alterations make some sort of difference. In the very same post, you mention how one of the changed lines "hits harder than most spelling and grammar errors."

> Also notice that no one complained about the robotic "It is you!" being altered despite being grammatically okay.

Even if someone had complained, what difference would it make? Your argument seems to chug along regardless.

**Comment by bansheexyz** [comment]
I'll revert for now, but we don't have the luxury of polling hundreds of people on this. I said from the beginning that people need to link grammar articles with protestations, not "I grew up poor and this sounds fine to me". I linked to an article (the #1 search result on google for omitting that) that states it can only be omitted after "say," "think," "know," "claim," "hear," and "believe." "Suppose" and "fault" are not on that list.

**Comment by tolbell** [comment]
https://englishharmony.com/omitting-relative-pronouns/

**Comment by Interkarma** [comment]
These are some good fixes @bansheexyz, thank you. :)

No problems on this end in tests so far, and everything looks good on a read. I'll get these merged within next couple of weekly releases.

**Pull request merged**
