### PR TITLE
Add IPlayerActivable interface for custom activations

### PR DESCRIPTION
**Pull request by TheLacus**
Added an interface which can be used to subscribe to custom player activations for any object. I'm personally going to use it for my harvesting mod where i need to detect when a crop is picked.

### CODE REVIEW

**Comment by JayH2971** [comment]
Does this include enemy entities?

**Comment by petchema** [comment]
is there some overlap with Hazelnut's ModelActivation, also in PlayerActivate?

**Comment by TheLacus** [comment]
> 
> 
> Does this include enemy entities?

It triggers a target on player action. It's the same thing used for doors, loot, npc talk functionalities etc.

> 
> 
> is there some overlap with Hazelnut's ModelActivation, also in PlayerActivate?

No, it has a different purpose, i think. It allows any object to detect player click, is not linked to model id. For example crops are billboard and not models so i can't use ModelActivation.

**Comment by TheLacus** [comment]
Actually i think it wouldn't be a bad idea to use an interface or abstract class for all core activations. Right now everything has its own check (with GetComponent) and this comes with a performance cost.

**Comment by ajrb** [comment]
> 
> 
> > Does this include enemy entities?
> 
> It triggers a target on player action. It's the same thing used for doors, loot, npc talk functionalities etc.
> 
> > is there some overlap with Hazelnut's ModelActivation, also in PlayerActivate?
> 
> No, it has a different purpose, i think. It allows any object to detect player click, is not linked to model id or any classic model data. For example crops are billboards and not models so i can't use ModelActivation.

How do you add this to your objects? The model activation works on existing DF objects from the game data using the model id, not sure how I would be able to use this interface instead without going though every scene after it's initialised and adding a component implementing this interface to every model with a certain id. Does your mod already do this or does it create new flats?

Very happy to move to a more general solution for custom activations if it's easy to do. My model activation regsitration was very specific to my needs.

**Comment by TheLacus** [comment]
I add a component that implements this interface to my prefabs. Existing plants are replaced by asset-injection framework; i wouldn't be able to make default crops harvestable anyway because they are batched.

I'm not suggesting to remove `ModelActivation`, i only added a more generic way to make an object interactable which is needed for new models added by mods.

**Comment by ajrb** [comment]
Looks good to me from reading the code.

**Comment by Interkarma** [comment]
This is a clever idea! Merging.

**Pull request merged**
