### PR TITLE
Make arrows use colliders for hit checks

### PR DESCRIPTION
**Pull request by Allofich**
Combined with https://github.com/Interkarma/daggerfall-unity/pull/1195, this fixes the other issue in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1751 (about the bats).

1. Use colliders instead of ray casts for arrows.
- Enemies pushed around ("Jedi reflexes" of the bug report) less
- Shooting enemies at point-blank range will register hits better now (will still go through them if they are right next to you, but that doesn't bother me too much as it is unrealistic to shoot from that close anyway)
- Maybe a little better performance?, since instead of doing raycasts the collider that existed on the arrows is used.
- Maybe more reliable hit detection, although the ray-cast solution seemed to be working for me except at point-blank ranges.

2. Moved arrow disabling and damage to be called immediately on collision instead of in the update loop
- Together with the above, seems to have (possibly) fixed completely the issue of enemies being pushed by the arrow

3. Can no longer bash doors with arrows, as it didn't make much sense

### CODE REVIEW

**Comment by Allofich** [comment]
Not sure if it really mattered, but arrows' 3d objects are destroyed now, not just disabled.

Also, maybe this PR will help with this issue: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1811. I've never had that issue happen before, but maybe using the collider will more reliably clean up the arrows.

**Comment by Interkarma** [comment]
Thank you!

**Comment by Allofich** [comment]
Should have mentioned, during testing this it seemed like the forced crouch from enemy arrows contacting with player may be exacerbated with this PR.

**Comment by Interkarma** [comment]
I have a fix in pipeline for that, but probably won't be ready for this weekend's builds. I'll see if I can add something faster.

**Pull request merged**
