### PR TITLE
Increase accessibility of Trade Window for modding purposes

### PR DESCRIPTION
**Pull request by AsesinoBlade**
Hi all,
I am taking advantage of The UIFactory to add my inventory filter as a mod.  I need to have some variables and a method switched to protected in order to extend the window.

Thank you for your consideration.
A

### CODE REVIEW

**Comment by df-ferital** [comment]
With small changes like that, my advise would be to squash all your commits down into a single one.

**Comment by ajrb** [comment]
Yeah I agree. 9 commits for as many lines is OTT. Other than that it looks fine to me.

**Comment by petchema** [comment]
PRs can be squashed at merge time, so that should be okay
MPR options

**Comment by AsesinoBlade** [comment]
Thanks all, I am unsure how I would squash it. I am happy to do so if someone can point me to an instruction guide. 

Thanks again all,
A

**Comment by TheLacus** [comment]
I made some changes. For example `usingWagon` is toggled by method `SelectWagon()` so setter shouldn't be private. There was also a field that was already exposed by a public property, so i restored private modifier.

Please tell me if you have everything to make your mod and i'll merge :)

**Comment by AsesinoBlade** [comment]
Hi @TheLacus, I tried out the changes ; it appears to work fine except for the get set WindowMode and Guild.  Maybe I am building my constructor incorrectly; I just copied the constructor for DaggerfallTradeWindow.

Here is my constructor:
`      public AsesinoTradeWindow(IUserInterfaceManager uiManager, DaggerfallBaseWindow previous = null, WindowModes windowMode = WindowModes.Sell, IGuild guild = null)
            : base(uiManager, previous)
        {
            this.WindowMode = windowMode;
            this.Guild = guild;
        }`
With the way I did it, i need to have access to set in order for the constructor to compile.

Other than that, it seems to work fine; I tested a few things out and it is working correctly.

Thanks again for all the help @TheLacus, I really appreciate it.
a

**Comment by ajrb** [comment]
`
public AsesinoTradeWindow(IUserInterfaceManager uiManager, DaggerfallBaseWindow previous = null, WindowModes windowMode = WindowModes.Sell, IGuild guild = null) : base(uiManager, previous, windowMode, guild) {
}`

You need to pass the constructor params into the base class.

**Comment by AsesinoBlade** [comment]
Thanks Arjb. I will try that when I get home. 
I appreciate the help. 
Thanks
A

**Pull request merged**
