### PR TITLE
Add several missing ui sounds (#1618 recovery)

### PR DESCRIPTION
**Pull request by petchema**
I still think all this work done by @D0ct0r3d is interesting, so I'm recovering #1618 .

I didn't fix indentation myself before because of bad experience with committing directly into other people's repository, but now I have no excuses anymore...

### CODE REVIEW

**Comment by Interkarma** [comment]
@D0ct0r3d My sincere apologies, as my earlier feedback seems to have resulted in PR being closed. It was never my intention to discourage, only to explain why the UI had reduced button clicks. I am willing to merge into game, and was only requesting a rework of formatting and fixing merge conflict before review. Thank you @petchema for taking care of that.

**Comment by Interkarma** [comment]
@petchema could I quickly get your help to resolve those few conflicts with changes made by hotkey system now that has merged? I will include this PR in next builds.

**Comment by petchema** [comment]
okay, working on it

**Comment by petchema** [comment]
should be fine again

**Comment by D0ct0r3d** [comment]
> @D0ct0r3d My sincere apologies, as my earlier feedback seems to have resulted in PR being closed. It was never my intention to discourage, only to explain why the UI had reduced button clicks. I am willing to merge into game, and was only requesting a rework of formatting and fixing merge conflict before review. Thank you @petchema for taking care of that.

Hey, no worries. :) I just misunderstood and assumed you really didn't want the sounds in the game in the first place. I didn't want to step on any toes. Personally, I think the game sounds better when it has feedback for all the actions like the original did. Then with the holidays and everything, I just figured it would be best if I closed it. 

@petchema Thanks :)

**Pull request merged**
