### PR TITLE
Optimize location loading

### PR DESCRIPTION
**Pull request by df-ferital**
Improve location loading by keeping the list of blocks related to a location inside `DFLocation`. I made this after I noticed `RMBLayout.GetLocationBuildingData` was called several times: when entering a town, when entering a building, when talking to a NPC, etc. Unfortunately, calling this method can be relatively heavy in large cities (around 0.150s on my computer). Furthermore, when loading a savegame or when travelling to a new location, the method can be called 4 or 5 times.

So, this PR improves performance while making a location buildings list accessible immediately, reducing code bloat and improving overall clarity. The only drawback comes from `Clock.GetTravelTimeInSeconds` which may become a little slower, since it does not require location buildings list, only location coordinates. However, this isn't really noticeable in game.

### CODE REVIEW

**Comment by petchema** [comment]
For some reason I still need
`using DaggerfallWorkshop.Utility.AssetInjection;`
in Assets/Scripts/API/MapsFile.cs, replaced in last commit, to compile this PR

**Comment by df-ferital** [comment]
This must be because I opened this quite some time ago, so it might need to be adjusted a little bit when working with last master revision. I will rebased it when I can.

**Comment by Interkarma** [comment]
I'm a bit worried about how this one will play with @ajrb's block replacement. This can switch environments around even at runtime (e.g. from a quest action), and there seems to be some danger of additional caching causing things to get out sync here.

Let me come back to this one after worldDataDev branch has been merged. I'll be looking at all these PRs soon with weekly builds. :)

**Comment by df-ferital** [comment]
No problem, as this is only an optimization, I will rebased it on last master revision when potential conflicting other PR will be merged. I'll also test it again :)

**Comment by ajrb** [comment]
How does this improve location loading performance? I don't see the GetLocationBuildingData being a significant amount of time when I profile location loading with the Unity profiler. Looks like most of the time is taken constructing the base block game objects, adding components and applying materials.

When I log the time taken by the SetLocation() call in StreamingWorld.UpdateLocation() using a stopwatch, it's mostly less than 5ms, with the longest time being 39ms for a large city (Daggerfall) and when compared to the total time to construct Daggerfall location being 2167ms I'm not convinced this is where we need to optimise things.

It may be that it helps in other places and I am taking your title too literally, and it may also be affected by using an SSD and modern CPU (Ryzen)

**Comment by df-ferital** [comment]
I don't have much time to work on this right now and I'm not sure it's still need. Also, I suppose I changed too many things in this PR, beyond its original scope, which was only to prevent several useless calls to `RMBLayout.GetLocationBuildingData`.

**Pull request closed without merging**
